import type { GameDefinition } from "@/features/gamification/types";

export const repertoireGames: GameDefinition[] = [
  {
    id: "repertoire-match",
    name: "Repertório por Eixo",
    category: "repertorio",
    description: "Arraste cada repertório (autor, obra, conceito ou caso) para o eixo temático em que ele rende mais na argumentação.",
    difficulty: "Avancado",
    xpReward: 74,
    estimatedTime: "6 min",
    thumbnail: "repertorio-contexto",
    progress: 0,
    unlocked: true,
    engine: "classify",
    skill: "Repertório produtivo",
    classify: {
      instruction: "Cada repertório se conecta melhor a um eixo. Classifique pensando em qual tema ele realmente esclarece.",
      buckets: [
        { id: "digital", label: "Tecnologia e desinformação", hint: "algoritmos, redes, dados" },
        { id: "urbano", label: "Desigualdade e território", hint: "cidade, acesso a direitos" },
        { id: "democracia", label: "Cidadania e democracia", hint: "direitos, participação, Estado" },
        { id: "cultura", label: "Cultura e identidade", hint: "memória, representação, sociedade" },
      ],
      items: [
        { id: "i1", text: "Escândalo da Cambridge Analytica", bucketId: "digital", explanation: "Uso de dados para direcionar mensagens políticas." },
        { id: "i2", text: "Conceito de 'bolha' / filtro-bolha (Eli Pariser)", bucketId: "digital" },
        { id: "i3", text: "LGPD (Lei Geral de Proteção de Dados)", bucketId: "digital" },
        { id: "i4", text: "Milton Santos e o 'meio técnico-científico-informacional'", bucketId: "urbano", explanation: "Território usado de forma desigual." },
        { id: "i5", text: "Direito à cidade (Henri Lefebvre)", bucketId: "urbano" },
        { id: "i6", text: "Constituição de 1988 e os direitos sociais", bucketId: "democracia" },
        { id: "i7", text: "Conceito de esfera pública (Habermas)", bucketId: "democracia", explanation: "Debate racional e formação da opinião pública." },
        { id: "i8", text: "Modernidade líquida (Zygmunt Bauman)", bucketId: "cultura", explanation: "Fragilidade dos vínculos na sociedade contemporânea." },
        { id: "i9", text: "Lugar de fala (Djamila Ribeiro)", bucketId: "cultura" },
        { id: "i10", text: "'Vigiar e Punir' (Michel Foucault)", bucketId: "democracia", explanation: "Mecanismos de controle e poder." },
      ],
    },
  },
  {
    id: "cultural-bridge",
    name: "Ponte Sociocultural",
    category: "repertorio",
    description: "Distinga o uso produtivo do repertório (que interpreta o problema) da citação decorativa (que apenas enfeita). Quiz aprofundado.",
    difficulty: "Avancado",
    xpReward: 70,
    estimatedTime: "6 min",
    thumbnail: "repertorio-ponte",
    progress: 0,
    unlocked: true,
    engine: "quiz",
    skill: "Articulação de repertório",
    questions: [
      {
        id: "q1",
        prompt: "Tema: vínculos digitais frágeis. Qual uso de repertório é mais produtivo?",
        options: [
          "Segundo Bauman, na modernidade líquida os laços se tornam descartáveis, o que ajuda a explicar a superficialidade das relações online.",
          "Bauman nasceu em 1925 e escreveu muitos livros importantes.",
          "Como diz o ditado, quem não tem cão caça com gato.",
          "A modernidade líquida é um conceito muito interessante e atual.",
        ],
        answerIndex: 0,
        explanation: "O repertório produtivo conecta o conceito ao problema discutido, gerando análise — não apenas menção.",
      },
      {
        id: "q2",
        prompt: "Qual citação está apenas decorativa (não articula com o argumento)?",
        options: [
          "Einstein dizia que a imaginação é mais importante que o conhecimento; por isso devemos reciclar o lixo.",
          "Conforme a Constituição, a educação é direito de todos, o que torna o abandono escolar uma violação concreta.",
          "Dados do IBGE mostram queda na leitura, evidenciando a urgência de políticas culturais.",
          "Milton Santos mostra que o território é usado de forma desigual, explicando a exclusão digital nas periferias.",
        ],
        answerIndex: 0,
        explanation: "A frase de Einstein não tem relação lógica com reciclagem: repertório descontextualizado.",
      },
      {
        id: "q3",
        prompt: "Tema: desinformação. Qual repertório é mais pertinente e bem articulado?",
        options: [
          "O caso da Cambridge Analytica revela como o uso indevido de dados pessoais pode manipular escolhas, reforçando a urgência da educação midiática.",
          "A internet foi criada no século XX e mudou o mundo.",
          "Fake news são notícias falsas que circulam muito.",
          "Todo mundo sabe que não se pode acreditar em tudo.",
        ],
        answerIndex: 0,
        explanation: "O caso concreto ilustra o mecanismo do problema e leva a um encaminhamento (educação midiática).",
      },
      {
        id: "q4",
        prompt: "Qual estratégia melhora a articulação de um dado estatístico?",
        options: [
          "Interpretar o dado, mostrando o que ele revela sobre o problema.",
          "Apresentar o número e mudar de assunto.",
          "Citar a fonte e repetir o número em outras palavras.",
          "Usar o dado só na conclusão, sem comentário.",
        ],
        answerIndex: 0,
        explanation: "Dado sem interpretação não argumenta; é a análise que transforma número em prova.",
      },
      {
        id: "q5",
        prompt: "Tema: direito à cidade. Qual uso de Milton Santos é mais analítico?",
        options: [
          "Para Milton Santos, o espaço é organizado segundo interesses econômicos, o que explica por que periferias carecem de infraestrutura digital.",
          "Milton Santos foi um importante geógrafo brasileiro.",
          "Milton Santos escreveu sobre o Brasil e o mundo.",
          "Segundo um geógrafo famoso, as cidades são complexas.",
        ],
        answerIndex: 0,
        explanation: "A formulação aplica o conceito ao recorte do tema, produzindo explicação causal.",
      },
      {
        id: "q6",
        prompt: "Qual repertório é inadequado por ser factualmente incorreto?",
        options: [
          "A Lei Áurea, de 1888, garantiu acesso universal à internet no Brasil.",
          "A LGPD regula o tratamento de dados pessoais no Brasil.",
          "A Declaração Universal dos Direitos Humanos data de 1948.",
          "O ECA protege crianças e adolescentes.",
        ],
        answerIndex: 0,
        explanation: "Repertório falso destrói a credibilidade: a Lei Áurea aboliu a escravidão, nada tem a ver com internet.",
      },
      {
        id: "q7",
        prompt: "Como integrar repertório à tese sem soar 'colado'?",
        options: [
          "Conectar o conceito ao problema com um operador argumentativo (porque, logo, assim).",
          "Inserir a citação isolada em um parágrafo só para ela.",
          "Abrir a redação com a citação sem comentá-la.",
          "Usar vários autores sem explicar nenhum.",
        ],
        answerIndex: 0,
        explanation: "Operadores argumentativos costuram o repertório ao raciocínio, evitando o 'enxerto'.",
      },
      {
        id: "q8",
        prompt: "Tema: cultura e identidade. Qual uso de 'lugar de fala' é mais produtivo?",
        options: [
          "O conceito de lugar de fala, de Djamila Ribeiro, ajuda a entender por que dar voz a grupos historicamente silenciados qualifica o debate público.",
          "Lugar de fala é quando alguém fala de um lugar.",
          "Djamila Ribeiro é uma filósofa brasileira contemporânea.",
          "Todo mundo tem o direito de falar o que quiser.",
        ],
        answerIndex: 0,
        explanation: "A formulação explica o conceito e o conecta ao efeito argumentativo desejado.",
      },
    ],
  },
  {
    id: "repertoire-rush",
    name: "Repertório Relâmpago",
    category: "repertorio",
    description: "Modo cronometrado: dado um tema, escolha rápido o repertório mais produtivo. Combo e velocidade crescente.",
    difficulty: "Avancado",
    xpReward: 72,
    estimatedTime: "Infinito",
    thumbnail: "repertorio-rush",
    progress: 0,
    unlocked: true,
    engine: "timed-rush",
    skill: "Seleção de repertório",
    questions: [
      {
        id: "q1",
        prompt: "Tema: manipulação por algoritmos. Repertório mais produtivo?",
        options: ["Cambridge Analytica", "Revolta da Vacina", "Arcadismo", "Tratado de Tordesilhas"],
        answerIndex: 0,
        explanation: "O caso ilustra o uso de dados para direcionar mensagens — exatamente o eixo do tema.",
      },
      {
        id: "q2",
        prompt: "Tema: desigualdade urbana e acesso a direitos. Autor mais produtivo?",
        options: ["Milton Santos", "Gregor Mendel", "Pero Vaz de Caminha", "Isaac Newton"],
        answerIndex: 0,
        explanation: "Milton Santos pensa território, cidadania e distribuição desigual de recursos.",
      },
      {
        id: "q3",
        prompt: "Tema: fragilidade dos vínculos na era digital. Repertório mais pertinente?",
        options: ["Modernidade líquida (Bauman)", "Teoria da relatividade", "Pirâmide de Maslow apenas como curiosidade", "Lei de Ohm"],
        answerIndex: 0,
        explanation: "Bauman explica relações instáveis e descartáveis na contemporaneidade.",
      },
      {
        id: "q4",
        prompt: "Tema: proteção de dados pessoais. Repertório jurídico mais direto?",
        options: ["LGPD", "Lei Áurea", "Lei Maria da Penha", "Estatuto do Idoso"],
        answerIndex: 0,
        explanation: "A LGPD regula o tratamento de dados pessoais no Brasil.",
      },
      {
        id: "q5",
        prompt: "Tema: debate público e formação de opinião. Conceito mais produtivo?",
        options: ["Esfera pública (Habermas)", "Seleção natural", "Tectônica de placas", "Função quadrática"],
        answerIndex: 0,
        explanation: "Habermas trata da esfera pública e do debate racional como base da democracia.",
      },
      {
        id: "q6",
        prompt: "Tema: representatividade de grupos silenciados. Repertório mais pertinente?",
        options: ["Lugar de fala (Djamila Ribeiro)", "Cogito de Descartes", "Mito da caverna apenas citado", "Revolução Industrial"],
        answerIndex: 0,
        explanation: "O conceito de lugar de fala discute voz e representação de grupos historicamente excluídos.",
      },
      {
        id: "q7",
        prompt: "Tema: mecanismos de vigilância e controle social. Repertório mais analítico?",
        options: ["'Vigiar e Punir' (Foucault)", "Lei da gravidade", "Pacto de São José apenas como data", "Barroco mineiro"],
        answerIndex: 0,
        explanation: "Foucault analisa disciplina, vigilância e poder — base para discutir controle social.",
      },
      {
        id: "q8",
        prompt: "Tema: educação como direito. Repertório jurídico mais sólido?",
        options: ["Constituição de 1988 (art. 205)", "Tratado de Tordesilhas", "Código de Hamurabi", "Bula Inter Coetera"],
        answerIndex: 0,
        explanation: "A Constituição assegura a educação como direito de todos e dever do Estado.",
      },
      {
        id: "q9",
        prompt: "Tema: exclusão digital nas periferias. Conceito geográfico mais produtivo?",
        options: ["Meio técnico-científico-informacional (Milton Santos)", "Deriva continental", "Ciclo da água", "Teorema de Pitágoras"],
        answerIndex: 0,
        explanation: "O conceito explica por que a técnica e a informação se distribuem de modo desigual no território.",
      },
      {
        id: "q10",
        prompt: "Tema: polarização e filtros de informação. Repertório mais pertinente?",
        options: ["Filtro-bolha (Eli Pariser)", "Lei de Lavoisier", "Romantismo brasileiro", "Conjuração Mineira"],
        answerIndex: 0,
        explanation: "O conceito de filtro-bolha explica o isolamento informacional gerado por algoritmos.",
      },
    ],
  },
];
