import type { GameDefinition } from "@/features/gamification/types";

export const repertoireGames: GameDefinition[] = [
  {
    id: "repertoire-match",
    name: "Repertório por Eixo",
    category: "repertorio",
    description: "Vários repertórios servem a mais de um tema. Arraste cada um para o eixo em que ele rende a análise MAIS produtiva — não apenas onde 'cabe'.",
    difficulty: "Avancado",
    xpReward: 78,
    estimatedTime: "6 min",
    thumbnail: "repertorio-contexto",
    progress: 0,
    unlocked: true,
    engine: "classify",
    skill: "Repertório produtivo",
    classify: {
      instruction: "Cada repertório poderia tangenciar vários temas. Escolha o eixo em que ele oferece o maior poder explicativo.",
      buckets: [
        { id: "vigilancia", label: "Vigilância e poder", hint: "controle, dados, disciplina" },
        { id: "espaco", label: "Espaço e desigualdade", hint: "território, cidade, acesso" },
        { id: "publico", label: "Esfera pública e debate", hint: "democracia, opinião, deliberação" },
        { id: "identidade", label: "Identidade e representação", hint: "voz, reconhecimento, cultura" },
      ],
      items: [
        { id: "i1", text: "Panóptico de Foucault ('Vigiar e Punir')", bucketId: "vigilancia", explanation: "Modelo de vigilância internalizada — rende mais em controle/poder que em mera 'tecnologia'." },
        { id: "i2", text: "Capitalismo de vigilância (Shoshana Zuboff)", bucketId: "vigilancia" },
        { id: "i3", text: "Direito à cidade (Henri Lefebvre)", bucketId: "espaco" },
        { id: "i4", text: "Meio técnico-científico-informacional (Milton Santos)", bucketId: "espaco", explanation: "Explica a distribuição desigual da técnica no território." },
        { id: "i5", text: "Ação comunicativa / esfera pública (Habermas)", bucketId: "publico" },
        { id: "i6", text: "Espiral do silêncio (Noelle-Neumann)", bucketId: "publico", explanation: "Trata da formação da opinião pública sob pressão da maioria percebida." },
        { id: "i7", text: "Lugar de fala (Djamila Ribeiro)", bucketId: "identidade" },
        { id: "i8", text: "Estigma (Erving Goffman)", bucketId: "identidade", explanation: "Identidade deteriorada e gestão da diferença — eixo de representação." },
        { id: "i9", text: "Necropolítica (Achille Mbembe)", bucketId: "vigilancia", explanation: "Poder de decidir quem vive e quem morre — eixo de poder, não só de violência urbana." },
        { id: "i10", text: "Modernidade líquida (Bauman)", bucketId: "identidade", explanation: "Fragilidade dos vínculos e da identidade contemporânea." },
      ],
    },
  },
  {
    id: "cultural-bridge",
    name: "Ponte Sociocultural",
    category: "repertorio",
    description: "Quatro usos do repertório, todos corretos — escolha o MAIS analítico, que interpreta o problema em vez de só ilustrá-lo.",
    difficulty: "Avancado",
    xpReward: 74,
    estimatedTime: "6 min",
    thumbnail: "repertorio-ponte",
    progress: 0,
    unlocked: true,
    engine: "quiz",
    skill: "Articulação de repertório",
    questions: [
      {
        id: "q1",
        prompt: "Tema: vínculos afetivos na era dos aplicativos. Qual emprego de Bauman é o MAIS analítico (não apenas pertinente)?",
        options: [
          "A 'modernidade líquida' de Bauman ilumina por que apps de relacionamento, ao tornar o outro substituível com um deslize de tela, normalizam o descarte afetivo.",
          "Bauman, em 'Modernidade Líquida', afirma que os laços contemporâneos são frágeis e instáveis.",
          "Para Bauman, vivemos tempos líquidos, o que se aplica bem às relações de hoje.",
          "Como mostra Bauman, tudo na pós-modernidade é fluido, inclusive o amor.",
        ],
        answerIndex: 0,
        explanation: "Só a 1ª aplica o conceito ao mecanismo concreto (substituibilidade por deslize), produzindo análise; as demais apenas parafraseiam o conceito.",
      },
      {
        id: "q2",
        prompt: "Tema: exclusão digital nas periferias. Qual uso de Milton Santos analisa, em vez de apenas citar?",
        options: [
          "Milton Santos mostra que o espaço é organizado segundo interesses econômicos; daí a infraestrutura digital concentrar-se onde há lucro, deixando a periferia em apagão informacional.",
          "Milton Santos foi um geógrafo que estudou o território brasileiro.",
          "Segundo Milton Santos, o espaço geográfico é importante para entender o país.",
          "Milton Santos diz que existem desigualdades no território nacional.",
        ],
        answerIndex: 0,
        explanation: "A 1ª converte o conceito em explicação causal do recorte; as outras são menção genérica sem operar sobre o problema.",
      },
      {
        id: "q3",
        prompt: "Qual alternativa comete erro de pertinência (repertório real, mas mal aplicado ao tema 'meritocracia')?",
        options: [
          "O mito de Sísifo, de Camus, prova que a meritocracia funciona porque o esforço sempre é recompensado.",
          "Para Bourdieu, o capital cultural herdado dá vantagem prévia, o que fragiliza a tese meritocrática.",
          "Jessé Souza discute como a 'ralé' brasileira é responsabilizada por sua própria exclusão.",
          "A noção de 'igualdade de oportunidades' pressupõe pontos de partida que não existem na prática.",
        ],
        answerIndex: 0,
        explanation: "Camus inverte-se: Sísifo simboliza o esforço absurdo e SEM recompensa — usá-lo para 'provar' meritocracia distorce a fonte.",
      },
      {
        id: "q4",
        prompt: "Tema: desinformação. Qual articulação evita o efeito 'enxerto' (citação colada)?",
        options: [
          "Esse cenário materializa a 'pós-verdade': como aponta o conceito, a adesão emocional supera a checagem factual, o que explica a viralização de boatos.",
          "Vivemos na era da pós-verdade. A internet mudou tudo. É preciso checar fatos.",
          "Pós-verdade é um conceito do dicionário Oxford de 2016.",
          "Muitos autores falam sobre pós-verdade atualmente.",
        ],
        answerIndex: 0,
        explanation: "A 1ª costura o conceito ao raciocínio com operador ('como aponta', 'o que explica'); as demais justapõem frases sem nexo argumentativo.",
      },
      {
        id: "q5",
        prompt: "Qual uso de dado estatístico é argumentativamente mais forte?",
        options: [
          "Se um quinto dos lares não tem internet, então políticas de ensino remoto, sem inclusão prévia, ampliam o fosso que pretendiam fechar.",
          "Dados do IBGE mostram que muitos lares não têm internet no Brasil.",
          "Um quinto dos lares brasileiros não possui acesso à internet, segundo o IBGE.",
          "As estatísticas comprovam que a internet não chega a todos.",
        ],
        answerIndex: 0,
        explanation: "Só a 1ª interpreta o dado (extrai uma consequência), transformando número em prova; as demais apenas o relatam.",
      },
      {
        id: "q6",
        prompt: "Tema: vigilância digital. Qual emprego de Foucault é mais produtivo?",
        options: [
          "O panóptico de Foucault explica por que, sabendo-se rastreado, o usuário autorregula seu comportamento online mesmo sem coerção explícita.",
          "Foucault escreveu 'Vigiar e Punir', um clássico sobre prisões.",
          "Segundo Foucault, o poder está em toda parte na sociedade.",
          "Foucault é um filósofo francês muito estudado nas universidades.",
        ],
        answerIndex: 0,
        explanation: "A 1ª transfere o mecanismo (vigilância internalizada) para o comportamento online; as demais são biografia ou paráfrase vaga.",
      },
      {
        id: "q7",
        prompt: "Qual repertório está factualmente INCORRETO e, portanto, comprometeria a redação?",
        options: [
          "A Lei Áurea (1888) instituiu o direito universal à educação digital.",
          "A LGPD (2018) disciplina o tratamento de dados pessoais no Brasil.",
          "O ECA (1990) protege crianças e adolescentes.",
          "A Declaração Universal dos Direitos Humanos data de 1948.",
        ],
        answerIndex: 0,
        explanation: "A Lei Áurea aboliu a escravidão; associá-la a 'educação digital' é erro factual grave.",
      },
      {
        id: "q8",
        prompt: "Tema: cultura do cancelamento. Qual uso de repertório melhor sustenta a análise?",
        options: [
          "A 'espiral do silêncio' explica por que, temendo o linchamento virtual, muitos calam opiniões dissonantes, empobrecendo o debate.",
          "O cancelamento é uma prática comum nas redes sociais hoje em dia.",
          "Noelle-Neumann foi uma pesquisadora alemã de opinião pública.",
          "As pessoas têm medo de falar o que pensam na internet.",
        ],
        answerIndex: 0,
        explanation: "A 1ª opera o conceito sobre o fenômeno (medo→silêncio→empobrecimento); as outras são senso comum ou biografia.",
      },
    ],
  },
  {
    id: "repertoire-rush",
    name: "Repertório Relâmpago",
    category: "repertorio",
    description: "Modo cronometrado: as quatro opções são repertórios legítimos — escolha rápido o MAIS pertinente ao recorte exato do tema. Combo e velocidade crescente.",
    difficulty: "Avancado",
    xpReward: 76,
    estimatedTime: "Infinito",
    thumbnail: "repertorio-rush",
    progress: 0,
    unlocked: true,
    engine: "timed-rush",
    skill: "Seleção de repertório",
    questions: [
      {
        id: "q1",
        prompt: "Recorte: autorregulação do comportamento sob rastreamento online. Repertório mais pertinente?",
        options: ["Panóptico (Foucault)", "Direito à cidade (Lefebvre)", "Modernidade líquida (Bauman)", "Esfera pública (Habermas)"],
        answerIndex: 0,
        explanation: "O panóptico trata exatamente da vigilância internalizada — mais direto que os demais, que tangenciam.",
      },
      {
        id: "q2",
        prompt: "Recorte: lucro obtido com a previsão e indução do comportamento por dados. Repertório mais preciso?",
        options: ["Capitalismo de vigilância (Zuboff)", "Indústria cultural (Adorno)", "Necropolítica (Mbembe)", "Estigma (Goffman)"],
        answerIndex: 0,
        explanation: "Zuboff cunhou o conceito para a monetização de dados comportamentais — encaixe exato.",
      },
      {
        id: "q3",
        prompt: "Recorte: silenciamento de opiniões minoritárias por medo do isolamento. Repertório mais pertinente?",
        options: ["Espiral do silêncio (Noelle-Neumann)", "Mão invisível (Adam Smith)", "Contrato social (Rousseau)", "Banalidade do mal (Arendt)"],
        answerIndex: 0,
        explanation: "A espiral do silêncio descreve precisamente esse mecanismo de autocensura.",
      },
      {
        id: "q4",
        prompt: "Recorte: vantagem escolar herdada que mina a meritocracia. Repertório mais preciso?",
        options: ["Capital cultural (Bourdieu)", "Darwinismo social (Spencer)", "Fordismo (Gramsci)", "Aldeia global (McLuhan)"],
        answerIndex: 0,
        explanation: "O capital cultural de Bourdieu explica a desigualdade de pontos de partida.",
      },
      {
        id: "q5",
        prompt: "Recorte: responsabilização do pobre por sua própria exclusão no Brasil. Repertório mais pertinente?",
        options: ["'A Ralé Brasileira' (Jessé Souza)", "Mito da democracia racial (apenas citado)", "Casa-grande & Senzala (Freyre)", "Utopia (Thomas More)"],
        answerIndex: 0,
        explanation: "Jessé Souza analisa diretamente a culpabilização das classes populares.",
      },
      {
        id: "q6",
        prompt: "Recorte: gestão estatal sobre quem pode viver e quem é deixado morrer. Repertório mais preciso?",
        options: ["Necropolítica (Mbembe)", "Biopoder genérico", "Leviatã (Hobbes)", "Fim da história (Fukuyama)"],
        answerIndex: 0,
        explanation: "Mbembe formula a 'necropolítica' exatamente para esse poder sobre a morte.",
      },
      {
        id: "q7",
        prompt: "Recorte: deterioração e gestão da identidade de grupos marcados socialmente. Repertório mais pertinente?",
        options: ["Estigma (Goffman)", "Anomia (Durkheim)", "Mais-valia (Marx)", "Indústria cultural (Adorno)"],
        answerIndex: 0,
        explanation: "'Estigma', de Goffman, trata da identidade deteriorada e do manejo da diferença.",
      },
      {
        id: "q8",
        prompt: "Recorte: padronização do gosto e do consumo cultural pela mídia de massa. Repertório mais preciso?",
        options: ["Indústria cultural (Adorno e Horkheimer)", "Lugar de fala (Djamila)", "Direito à cidade (Lefebvre)", "Panóptico (Foucault)"],
        answerIndex: 0,
        explanation: "A indústria cultural descreve a homogeneização do consumo cultural.",
      },
      {
        id: "q9",
        prompt: "Recorte: deliberação racional como base da legitimidade democrática. Repertório mais pertinente?",
        options: ["Ação comunicativa (Habermas)", "Vontade de potência (Nietzsche)", "Capital cultural (Bourdieu)", "Necropolítica (Mbembe)"],
        answerIndex: 0,
        explanation: "Habermas fundamenta a legitimidade no debate racional da esfera pública.",
      },
      {
        id: "q10",
        prompt: "Recorte: produção desigual do espaço urbano segundo interesses econômicos. Repertório mais preciso?",
        options: ["Direito à cidade (Lefebvre)", "Espiral do silêncio (Noelle-Neumann)", "Estigma (Goffman)", "Pós-verdade (Oxford)"],
        answerIndex: 0,
        explanation: "Lefebvre discute a apropriação desigual e a mercantilização do espaço urbano.",
      },
    ],
  },
];
