import type { GameDefinition } from "@/features/gamification/types";

export const challengeGames: GameDefinition[] = [
  {
    id: "daily-mixed-rush",
    name: "Desafio Relâmpago",
    category: "desafios-diarios",
    description: "Modo cronometrado misto: conectivo, tese, repertório e gramática numa só rodada. Mantenha o combo vivo.",
    difficulty: "Avancado",
    xpReward: 80,
    estimatedTime: "Infinito",
    thumbnail: "daily-rush",
    progress: 0,
    unlocked: true,
    engine: "timed-rush",
    skill: "Revisão geral",
    questions: [
      {
        id: "q1",
        prompt: "A escola amplia repertórios; ___, nem sempre ensina a usá-los na argumentação.",
        options: ["contudo", "portanto", "assim", "logo"],
        answerIndex: 0,
        explanation: "Relação de oposição entre ampliar e saber usar.",
      },
      {
        id: "q2",
        prompt: "Qual frase respeita a norma-padrão?",
        options: [
          "Fazem dez anos que estudo aqui.",
          "Faz dez anos que estudo aqui.",
          "Houveram problemas no sistema.",
          "Os aluno chegaram cedo.",
        ],
        answerIndex: 1,
        explanation: "'Fazer' indicando tempo é impessoal: 'Faz dez anos'.",
      },
      {
        id: "q3",
        prompt: "Tema: desinformação. Melhor tese?",
        options: [
          "A ausência de educação midiática facilita a circulação de notícias falsas.",
          "Fake news são ruins.",
          "A internet mudou tudo.",
          "As pessoas mentem muito.",
        ],
        answerIndex: 0,
        explanation: "Tese com recorte (educação midiática) e consequência.",
      },
      {
        id: "q4",
        prompt: "Repertório mais produtivo para 'proteção de dados':",
        options: ["LGPD", "Lei Áurea", "Arcadismo", "Tratado de Tordesilhas"],
        answerIndex: 0,
        explanation: "A LGPD regula o tratamento de dados pessoais no Brasil.",
      },
      {
        id: "q5",
        prompt: "Qual período está bem pontuado?",
        options: [
          "Os estudantes, da rede pública merecem apoio.",
          "Os estudantes da rede pública merecem apoio.",
          "Os estudantes da rede pública, merecem apoio.",
          "Os estudantes da, rede pública merecem apoio.",
        ],
        answerIndex: 1,
        explanation: "Não se separa sujeito de verbo por vírgula.",
      },
      {
        id: "q6",
        prompt: "'Estudou muito; ___, foi aprovado.' Qual conectivo conclui?",
        options: ["portanto", "embora", "à medida que", "ainda que"],
        answerIndex: 0,
        explanation: "Relação de conclusão entre esforço e resultado.",
      },
      {
        id: "q7",
        prompt: "Qual proposta de intervenção é mais completa?",
        options: [
          "O MEC deve ampliar bibliotecas, por meio de parcerias, a fim de incentivar a leitura.",
          "O governo deve ajudar mais.",
          "As pessoas precisam se conscientizar.",
          "É preciso melhorar a educação.",
        ],
        answerIndex: 0,
        explanation: "Apresenta agente, ação, meio e finalidade.",
      },
      {
        id: "q8",
        prompt: "Qual frase tem erro de regência?",
        options: [
          "Prefiro cinema do que teatro.",
          "Prefiro cinema a teatro.",
          "Obedeço às normas.",
          "Assisti ao filme ontem.",
        ],
        answerIndex: 0,
        explanation: "'Preferir' rege 'a', sem 'do que': 'prefiro X a Y'.",
      },
      {
        id: "q9",
        prompt: "'A medida é polêmica, ___ necessária.' Qual conectivo cabe?",
        options: ["porém", "porque", "portanto", "para que"],
        answerIndex: 0,
        explanation: "Contraste entre 'polêmica' e 'necessária': adversativo.",
      },
      {
        id: "q10",
        prompt: "Qual é uma constatação, e não uma tese?",
        options: [
          "A violência urbana aumentou nos últimos anos.",
          "A falta de prevenção alimenta a violência urbana.",
          "A desigualdade é raiz da violência urbana.",
          "A precarização do espaço público intensifica a insegurança.",
        ],
        answerIndex: 0,
        explanation: "Constatar um fato não defende um ponto de vista.",
      },
    ],
  },
  {
    id: "daily-fill",
    name: "Lacuna do Dia",
    category: "desafios-diarios",
    description: "Digite o conectivo ou termo que completa cada período. Treino rápido de precisão, sem alternativas.",
    difficulty: "Intermediario",
    xpReward: 54,
    estimatedTime: "4 min",
    thumbnail: "daily-fill",
    progress: 0,
    unlocked: true,
    engine: "fill-blank",
    skill: "Precisão lexical",
    fillBlank: {
      rounds: [
        {
          id: "r1",
          prompt: "Conclusão: 'O investimento foi alto; ___, os resultados apareceram.' (conectivo conclusivo de 8 letras)",
          accepted: ["portanto"],
          explanation: "Relação de conclusão/consequência: 'portanto'.",
        },
        {
          id: "r2",
          prompt: "Oposição: 'A meta era difícil, ___ a equipe a cumpriu.' (conectivo adversativo de 3 letras)",
          accepted: ["mas"],
          explanation: "Contraste: 'mas'.",
        },
        {
          id: "r3",
          prompt: "Causa: 'A política deve ser contínua, ___ a educação dá frutos no longo prazo.' (locução causal: 'visto ___')",
          accepted: ["visto que", "que", "porque", "uma vez que", "ja que", "já que"],
          explanation: "Relação de causa/justificativa.",
        },
        {
          id: "r4",
          prompt: "Adição: 'A leitura amplia o vocabulário; ___, melhora a argumentação.' (locução de adição com 'além')",
          accepted: ["alem disso", "além disso"],
          explanation: "Soma de argumentos no mesmo sentido: 'além disso'.",
        },
        {
          id: "r5",
          prompt: "Finalidade: 'Ampliou-se o acervo ___ incentivar a leitura.' (locução de finalidade: 'a ___ de')",
          accepted: ["a fim de", "para", "com o objetivo de", "com a finalidade de"],
          explanation: "Indica objetivo: 'a fim de'.",
        },
        {
          id: "r6",
          prompt: "Concessão: '___ a tecnologia avance, a formação docente é lenta.' (conjunção concessiva de 6 letras)",
          accepted: ["embora", "conquanto", "posto que"],
          explanation: "Concessão: 'embora'.",
        },
      ],
    },
  },
  {
    id: "daily-order",
    name: "Sequência do Dia",
    category: "desafios-diarios",
    description: "Ordene rapidamente a estrutura de um parágrafo ou de uma redação. Treino de organização textual.",
    difficulty: "Intermediario",
    xpReward: 56,
    estimatedTime: "4 min",
    thumbnail: "daily-order",
    progress: 0,
    unlocked: true,
    engine: "order",
    skill: "Organização textual",
    order: {
      rounds: [
        {
          id: "r1",
          instruction: "Ordene a estrutura de uma redação dissertativa-argumentativa.",
          items: [
            "Introdução com contextualização e tese",
            "Primeiro parágrafo de desenvolvimento",
            "Segundo parágrafo de desenvolvimento",
            "Conclusão com proposta de intervenção",
          ],
          explanation: "A macroestrutura padrão do ENEM: introdução, dois desenvolvimentos e conclusão.",
        },
        {
          id: "r2",
          instruction: "Ordene os elementos de uma proposta de intervenção.",
          items: [
            "Agente (quem faz)",
            "Ação (o que faz)",
            "Meio (como faz)",
            "Finalidade (para quê)",
          ],
          explanation: "A ordem mais comum da proposta: agente → ação → meio → finalidade (+ detalhamento).",
        },
        {
          id: "r3",
          instruction: "Ordene um parágrafo de desenvolvimento.",
          items: [
            "Tópico frasal apresentando o argumento",
            "Explicação que desenvolve a ideia",
            "Repertório ou dado que comprova",
            "Arremate que conecta à tese",
          ],
          explanation: "Tópico → explicação → comprovação → arremate dá progressão ao parágrafo.",
        },
      ],
    },
  },
];
