import type { GameDefinition } from "@/features/gamification/types";

export const challengeGames: GameDefinition[] = [
  {
    id: "daily-mixed-rush",
    name: "Desafio Relâmpago",
    category: "desafios-diarios",
    description: "Modo cronometrado misto e exigente: semântica de conectivos, regência, tese, repertório e falácia numa só rodada. Todas as opções são plausíveis.",
    difficulty: "Avancado",
    estimatedTime: "Infinito",
    thumbnail: "daily-rush",
    progress: 0,
    unlocked: true,
    engine: "timed-rush",
    skill: "Revisão geral",
    questions: [
      {
        id: "q1",
        prompt: "'A escola amplia repertórios; ___, raramente ensina a articulá-los na argumentação.' Qual conectivo?",
        options: ["entretanto", "porquanto", "à medida que", "destarte"],
        answerIndex: 0,
        explanation: "Contraste entre ampliar e não ensinar a usar: adversativo. 'Porquanto' (causa), 'destarte' (conclusão).",
      },
      {
        id: "q2",
        prompt: "Qual frase respeita a regência culta?",
        options: [
          "Aspiro ao cargo de coordenador.",
          "Prefiro ficar do que sair.",
          "Assisti o jogo pela TV.",
          "Cheguei na escola atrasado.",
        ],
        answerIndex: 0,
        explanation: "'Aspirar' (almejar) é transitivo indireto: 'aspiro ao cargo'. As outras erram regência ('preferir a', 'assistir ao', 'chegar a').",
      },
      {
        id: "q3",
        prompt: "Tema: meritocracia. Qual é a melhor tese?",
        options: [
          "A retórica meritocrática, ao ignorar pontos de partida desiguais, culpabiliza o indivíduo por falhas estruturais.",
          "A meritocracia divide opiniões na sociedade.",
          "Nem todo esforço é recompensado de forma justa.",
          "O mérito importa, mas há desigualdades a considerar.",
        ],
        answerIndex: 0,
        explanation: "Só a 1ª nomeia o mecanismo e a consequência; as demais são vagas.",
      },
      {
        id: "q4",
        prompt: "Recorte: autorregulação do comportamento sob vigilância online. Repertório mais pertinente?",
        options: ["Panóptico (Foucault)", "Mão invisível (Smith)", "Modernidade líquida (Bauman)", "Direito à cidade (Lefebvre)"],
        answerIndex: 0,
        explanation: "O panóptico trata exatamente da vigilância internalizada.",
      },
      {
        id: "q5",
        prompt: "'Quem critica a reforma quer, no fundo, o caos.' Qual falácia?",
        options: ["Espantalho", "Falsa causa", "Apelo à autoridade", "Petição de princípio"],
        answerIndex: 0,
        explanation: "Distorce a posição do oponente para atacar uma versão caricata — espantalho.",
      },
      {
        id: "q6",
        prompt: "Qual período está corretamente pontuado?",
        options: [
          "O réu, que confessou, foi absolvido.",
          "O réu que confessou, foi absolvido.",
          "O réu, que confessou foi absolvido.",
          "O réu que, confessou, foi absolvido.",
        ],
        answerIndex: 0,
        explanation: "A oração explicativa exige vírgulas de abertura e fechamento.",
      },
      {
        id: "q7",
        prompt: "'É justo ___ trata desiguais de modo desigual.' Qual conectivo dá valor causal-explicativo?",
        options: ["na medida em que", "à medida que", "a fim de que", "conquanto"],
        answerIndex: 0,
        explanation: "'Na medida em que' = porque (causal); 'à medida que' seria proporção temporal.",
      },
      {
        id: "q8",
        prompt: "Qual frase apresenta erro de concordância?",
        options: [
          "Deve haver razões para a recusa.",
          "Hão de surgir oportunidades.",
          "Devem haver motivos ocultos.",
          "Existem soluções melhores.",
        ],
        answerIndex: 2,
        explanation: "'Haver' (existir) é impessoal e não pluraliza o auxiliar: 'deve haver'. 'Haver de' (=ir) flexiona: 'hão de surgir' está certa.",
      },
      {
        id: "q9",
        prompt: "Tema: fake news. Qual tese é mais analítica?",
        options: [
          "A arquitetura das plataformas, ao premiar engajamento em vez de veracidade, incentiva economicamente a desinformação.",
          "As fake news são um problema grave hoje.",
          "Muita gente acredita em boatos na internet.",
          "É preciso combater a desinformação nas redes.",
        ],
        answerIndex: 0,
        explanation: "A 1ª revela o mecanismo estrutural (incentivo econômico do design).",
      },
      {
        id: "q10",
        prompt: "'Ninguém provou que o aditivo faz mal; logo, é seguro.' Qual falácia?",
        options: ["Apelo à ignorância", "Falso dilema", "Ad hominem", "Derrapagem"],
        answerIndex: 0,
        explanation: "Ausência de prova de dano não prova segurança — apelo à ignorância.",
      },
    ],
  },
  {
    id: "daily-fill",
    name: "Lacuna do Dia",
    category: "desafios-diarios",
    description: "Digite o conectivo ou termo que completa cada período com precisão. Sem alternativas e sem dicas — domínio real exigido.",
    difficulty: "Avancado",
    estimatedTime: "5 min",
    thumbnail: "daily-fill",
    progress: 0,
    unlocked: true,
    engine: "fill-blank",
    skill: "Precisão lexical",
    fillBlank: {
      rounds: [
        {
          id: "r1",
          prompt: "Conformidade: 'Agiu ___ determina a lei, sem improvisos.' (conjunção de conformidade)",
          accepted: ["consoante", "conforme", "segundo"],
          explanation: "'Consoante/conforme/segundo' = conformidade (de acordo com).",
        },
        {
          id: "r2",
          prompt: "Concessão: '___ dispusesse de poucos recursos, entregou um projeto exemplar.' (conjunção concessiva)",
          accepted: ["embora", "conquanto", "ainda que", "posto que", "mesmo que", "se bem que"],
          explanation: "Concessão = contraria a expectativa: 'embora', 'conquanto', 'ainda que'.",
        },
        {
          id: "r3",
          prompt: "Causa: 'A audiência foi adiada, ___ faltou quórum.' (conjunção causal, não 'porque')",
          accepted: ["pois", "porquanto", "visto que", "uma vez que", "ja que", "já que", "haja vista que"],
          explanation: "Causa/explicação: 'pois', 'porquanto', 'visto que' etc.",
        },
        {
          id: "r4",
          prompt: "Consequência: 'Falou tão baixo ___ ninguém o ouviu.' (conjunção consecutiva)",
          accepted: ["que"],
          explanation: "Estrutura 'tão... que' = consecutiva (intensidade + resultado).",
        },
        {
          id: "r5",
          prompt: "Retificação: 'O problema não é técnico, ___ político.' (conjunção que corrige)",
          accepted: ["mas sim", "mas", "e sim", "porem", "porém"],
          explanation: "Correlação adversativa de retificação: 'não... mas sim'.",
        },
        {
          id: "r6",
          prompt: "Proporção: 'A confiança nas instituições cai ___ aumentam os escândalos.' (locução proporcional)",
          accepted: ["a medida que", "à medida que", "na proporcao em que", "à proporção que", "a proporcao que"],
          explanation: "Variação simultânea de grandezas: 'à medida que'.",
        },
      ],
    },
  },
  {
    id: "daily-order",
    name: "Sequência do Dia",
    category: "desafios-diarios",
    description: "Ordene cadeias argumentativas e estruturas textuais com coesão sutil. Várias ordens parecem válidas — só uma encadeia.",
    difficulty: "Avancado",
    estimatedTime: "5 min",
    thumbnail: "daily-order",
    progress: 0,
    unlocked: true,
    engine: "order",
    skill: "Organização textual",
    order: {
      rounds: [
        {
          id: "r1",
          instruction: "Ordene o argumento (dado → garantia → conclusão), atento aos conectivos.",
          items: [
            "Metade das cidades brasileiras não tem plano de saneamento (dado).",
            "Sem saneamento, doenças de veiculação hídrica proliferam (garantia).",
            "Portanto, a omissão no saneamento é também uma política de saúde fracassada (conclusão).",
          ],
          explanation: "Dado sustenta; garantia liga; 'portanto' conclui. Inverter dado e garantia rompe a lógica.",
        },
        {
          id: "r2",
          instruction: "Ordene o parágrafo respeitando a catáfora inicial.",
          items: [
            "Uma contradição define o debate sobre redes sociais.",
            "Elas ampliam a liberdade de expressão como nunca antes.",
            "Ao mesmo tempo, concentram em poucas empresas o poder de moderar o discurso.",
            "Esse paradoxo, portanto, exige regulação atenta à liberdade e ao abuso.",
          ],
          explanation: "O 1º anuncia 'uma contradição' (catáfora); os 2º e 3º a explicitam; o 4º a encapsula ('esse paradoxo') e conclui.",
        },
        {
          id: "r3",
          instruction: "Ordene os elementos da proposta de intervenção.",
          items: [
            "O Ministério da Saúde (agente)",
            "deve ampliar a atenção primária (ação)",
            "por meio de equipes itinerantes (meio)",
            "a fim de alcançar regiões remotas (finalidade)",
            "priorizando a Amazônia Legal (detalhamento)",
          ],
          explanation: "Agente → ação → meio → finalidade → detalhamento: ordem canônica da Competência 5.",
        },
      ],
    },
  },
];
