import type { GameDefinition } from "@/features/gamification/types";

export const grammarGames: GameDefinition[] = [
  {
    id: "grammar-hunt",
    name: "Caça ao Desvio",
    category: "gramatica",
    description:
      "Modo cronometrado: três frases corretas (algumas parecem erradas, mas não são) e uma com desvio real. Concordância, regência, crase, colocação e paralelismo no nível de banca.",
    difficulty: "Avancado",
    xpReward: 78,
    estimatedTime: "Infinito",
    thumbnail: "gramatica-revisao",
    progress: 0,
    unlocked: true,
    engine: "timed-rush",
    skill: "Norma culta",
    questions: [
      {
        id: "q1",
        prompt: "Qual frase apresenta DESVIO de norma culta?",
        options: [
          "Hão de existir soluções melhores do que esta.",
          "Devem haver soluções melhores do que esta.",
          "Faz anos que não a vejo.",
          "Sei que existem alternativas viáveis.",
        ],
        answerIndex: 1,
        explanation: "'Haver' (=existir) é impessoal; o auxiliar também não flexiona: 'Deve haver'. As outras estão corretas.",
      },
      {
        id: "q2",
        prompt: "Qual frase está INCORRETA quanto à regência?",
        options: [
          "Prefiro caminhar a correr.",
          "Visei o cargo a vida toda.",
          "Aspiro ao cargo de diretor.",
          "Namoro o vizinho há um ano.",
        ],
        answerIndex: 1,
        explanation: "No sentido de 'almejar', 'visar' é transitivo indireto: 'visei ao cargo'. 'Namorar' é transitivo direto (sem 'com'), e está correta.",
      },
      {
        id: "q3",
        prompt: "Em qual frase o uso (ou ausência) da crase está ERRADO?",
        options: [
          "Refiro-me àquela proposta.",
          "Cheguei a casa cedo.",
          "Entreguei o laudo a Vossa Senhoria.",
          "Pagamentos somente à vista de hoje à dez horas.",
        ],
        answerIndex: 3,
        explanation: "'às dez horas' exige crase (horas determinadas); 'à dez' está errado. 'a casa' (sem adjunto) e 'a Vossa Senhoria' dispensam crase, corretas.",
      },
      {
        id: "q4",
        prompt: "Qual frase viola o paralelismo sintático?",
        options: [
          "Ele gosta de ler e de escrever.",
          "Ela quer não só reconhecimento, mas também que a promovam.",
          "Quero saúde, paz e prosperar na vida.",
          "Estudar e descansar são igualmente necessários.",
        ],
        answerIndex: 2,
        explanation: "Coordena-se substantivos ('saúde, paz') com oração ('prosperar') — quebra de paralelismo. As demais mantêm estruturas equivalentes.",
      },
      {
        id: "q5",
        prompt: "Qual frase apresenta ERRO de concordância?",
        options: [
          "Bastava-lhe dois argumentos sólidos.",
          "Tratava-se de questões delicadas.",
          "Fazia dias que ninguém aparecia.",
          "Houve protestos em várias capitais.",
        ],
        answerIndex: 0,
        explanation: "'Bastar' tem sujeito ('dois argumentos'): concorda no plural — 'Bastavam-lhe'. 'Tratar-se de' e 'fazer' (tempo) são impessoais, corretas.",
      },
      {
        id: "q6",
        prompt: "Qual frase está INADEQUADA na colocação pronominal (norma culta)?",
        options: [
          "Em se tratando de prazos, sejamos rígidos.",
          "Me parece que houve engano.",
          "Tudo se resolverá a tempo.",
          "Nunca me disseram a verdade.",
        ],
        answerIndex: 1,
        explanation: "Não se inicia período com próclise na norma culta: 'Parece-me'. 'Em se tratando' é próclise consagrada após preposição 'em'; as outras estão certas.",
      },
      {
        id: "q7",
        prompt: "Qual frase contém ERRO de concordância nominal?",
        options: [
          "Seguem anexos os documentos.",
          "É proibida a entrada de estranhos.",
          "Elas mesmas resolveram o caso.",
          "Comprei bastantes livros e bastante revistas.",
        ],
        answerIndex: 3,
        explanation: "Como pronome indefinido, 'bastante' concorda: 'bastantes revistas'. As outras (anexos, proibida determinada, elas mesmas) estão corretas.",
      },
      {
        id: "q8",
        prompt: "Qual frase está ERRADA quanto ao acento indicativo de crase?",
        options: [
          "Refiro-me à Vossa Excelência.",
          "Dei o recado à senhora.",
          "Cheguei àquele impasse de novo.",
          "Voltei à terra natal.",
        ],
        answerIndex: 0,
        explanation: "Não há crase antes de pronome de tratamento: 'a Vossa Excelência'. 'à senhora', 'àquele' e 'à terra (natal)' estão corretas.",
      },
      {
        id: "q9",
        prompt: "Qual período apresenta ambiguidade estrutural (defeito de construção)?",
        options: [
          "Vi o incêndio voltando para casa.",
          "Quando voltava para casa, vi o incêndio.",
          "Vi, ao voltar para casa, o incêndio.",
          "O incêndio foi visto por mim na volta.",
        ],
        answerIndex: 0,
        explanation: "'voltando para casa' pode modificar 'eu' ou 'o incêndio' — ambiguidade. As reescritas desfazem a dupla leitura.",
      },
      {
        id: "q10",
        prompt: "Qual frase desrespeita a regência nominal?",
        options: [
          "Tenho aversão a multidões.",
          "É um livro acessível a todos.",
          "Sua resposta foi pertinente ao tema.",
          "Tenho preferência por teatro do que por cinema.",
        ],
        answerIndex: 3,
        explanation: "'Preferência' rege 'a': 'preferência por teatro a cinema' (sem 'do que'). As demais regências estão corretas.",
      },
      {
        id: "q11",
        prompt: "Qual frase contém ERRO de concordância verbal com sujeito partitivo/porcentagem?",
        options: [
          "A maioria dos alunos faltou.",
          "Cerca de 30% da turma desistiram.",
          "Um terço dos votos foi anulado.",
          "1% dos eleitores compareceram.",
        ],
        answerIndex: 3,
        explanation: "Com '1%', o verbo fica no singular: 'compareceu'. Em '30% da turma' admite-se plural por concordância com 'turma' — aceitável.",
      },
      {
        id: "q12",
        prompt: "Qual frase emprega MAL a partícula 'se'?",
        options: [
          "Tratam-se de assuntos urgentes.",
          "Vendem-se casas nesta rua.",
          "Precisa-se de vendedores experientes.",
          "Assistiu-se a cenas lamentáveis.",
        ],
        answerIndex: 0,
        explanation: "'Tratar-se de' é impessoal e invariável: 'Trata-se de assuntos'. 'Vendem-se casas' (passiva sintética) flexiona corretamente; as demais são índices de indeterminação corretos.",
      },
      {
        id: "q13",
        prompt: "Qual frase está ERRADA quanto ao uso do porquê?",
        options: [
          "Eis o porquê de sua recusa.",
          "Não revelou por que motivo desistiu.",
          "Ele se calou, por quê?",
          "Fiquei calado porque não sabia por quê responder.",
        ],
        answerIndex: 3,
        explanation: "Antes de verbo no interior da frase usa-se 'por que' (separado, sem acento): 'por que responder'. As outras estão corretas.",
      },
      {
        id: "q14",
        prompt: "Qual frase fere a concordância com o verbo 'ser'?",
        options: [
          "Tudo são flores no início.",
          "Hoje são dez de maio.",
          "A maioria eram estrangeiros.",
          "Cada um dos itens custam dez reais.",
        ],
        answerIndex: 3,
        explanation: "'Cada um' impõe singular: 'custa dez reais'. As demais (predicativo plural com 'ser', datas, partitivo) admitem o plural empregado.",
      },
      {
        id: "q15",
        prompt: "Qual período está INCORRETO quanto à pontuação?",
        options: [
          "Os alunos, exaustos, abandonaram a prova.",
          "Comprei, na feira, frutas e verduras.",
          "O réu, que confessou o crime foi condenado.",
          "Maria, a coordenadora, assinou o ofício.",
        ],
        answerIndex: 2,
        explanation: "A oração adjetiva explicativa exige vírgula de abertura E de fechamento: 'O réu, que confessou o crime, foi condenado.'",
      },
      {
        id: "q16",
        prompt: "Qual frase apresenta desvio de regência verbal?",
        options: [
          "Implicou mudanças profundas no setor.",
          "Chamou-lhe de incompetente.",
          "Custou-me admitir o erro.",
          "Procedeu a uma longa investigação.",
        ],
        answerIndex: 1,
        explanation: "'Chamar' (=apelidar) pede objeto direto + predicativo: 'chamou-o de incompetente' (não 'lhe'). As outras estão corretas.",
      },
    ],
  },
  {
    id: "comma-surgeon",
    name: "Cirurgia de Vírgula",
    category: "gramatica",
    description: "Pontuação que muda o sentido. Digite a palavra após a qual a vírgula resolve a ambiguidade, isola o termo deslocado ou marca a oração explicativa. Sem alternativas.",
    difficulty: "Avancado",
    xpReward: 68,
    estimatedTime: "6 min",
    thumbnail: "gramatica-pontuacao",
    progress: 0,
    unlocked: true,
    engine: "fill-blank",
    skill: "Pontuação e sentido",
    fillBlank: {
      rounds: [
        {
          id: "r1",
          prompt:
            "Oração explicativa: 'Os candidatos que mentiram foram desclassificados — sendo que TODOS mentiram.' Para tornar a adjetiva explicativa, após qual palavra entra a 1ª vírgula?",
          accepted: ["candidatos"],
          explanation: "Explicativa isola-se: 'Os candidatos, que mentiram, foram desclassificados' (todos). Sem vírgula, vira restritiva (só os que mentiram).",
        },
        {
          id: "r2",
          prompt: "Adjunto deslocado longo: 'Durante a pandemia de 2020 ___ as escolas migraram para o ensino remoto.' Após qual palavra entra a vírgula?",
          accepted: ["2020"],
          explanation: "O adjunto adverbial deslocado e extenso é isolado: 'Durante a pandemia de 2020, as escolas...'.",
        },
        {
          id: "r3",
          prompt: "Vocativo: 'Espero ___ senhores deputados ___ que aprovem a emenda.' Após qual palavra entra a 1ª vírgula que isola o vocativo?",
          accepted: ["espero"],
          explanation: "Vocativo intercalado é isolado por vírgulas: 'Espero, senhores deputados, que aprovem...'.",
        },
        {
          id: "r4",
          prompt:
            "Conjunção deslocada: 'A proposta era boa; a execução ___ porém ___ foi desastrosa.' Após qual palavra entra a 1ª vírgula que isola 'porém'?",
          accepted: ["execucao", "execução"],
          explanation: "'Porém' deslocado para o interior é isolado: 'a execução, porém, foi desastrosa'.",
        },
        {
          id: "r5",
          prompt: "Elipse do verbo: 'Uns defendiam a greve; outros ___ a rejeitavam.' Após qual palavra entra a vírgula que marca a elipse/contraste?",
          accepted: ["outros"],
          explanation: "A vírgula marca a estrutura paralela com apagamento: 'outros, a rejeitavam' (recurso de simetria; em registro formal, indica o contraste).",
        },
        {
          id: "r6",
          prompt:
            "Desfazer ambiguidade: 'Não compareceu porque estava doente.' Para garantir a leitura 'ele compareceu, mas não por estar doente', após qual palavra entra a vírgula?",
          accepted: ["compareceu"],
          explanation: "A vírgula antes de 'porque' altera o escopo da negação: 'Não compareceu, porque estava doente' (negação recai sobre a causa).",
        },
        {
          id: "r7",
          prompt: "Aposto explicativo: 'Drummond ___ poeta itabirano ___ revolucionou a lírica brasileira.' Após qual palavra entra a 1ª vírgula?",
          accepted: ["drummond"],
          explanation: "O aposto explicativo é isolado por vírgulas: 'Drummond, poeta itabirano, revolucionou...'.",
        },
        {
          id: "r8",
          prompt:
            "Oração coordenada com sujeitos diferentes: 'O juiz leu a sentença ___ e os réus se calaram.' Após qual palavra entra a vírgula opcional que separa as orações de sujeitos distintos?",
          accepted: ["sentenca", "sentença"],
          explanation: "Com sujeitos diferentes antes do 'e', admite-se vírgula: 'O juiz leu a sentença, e os réus se calaram.'",
        },
      ],
    },
  },
  {
    id: "register-classify",
    name: "Tipologia do Desvio",
    category: "gramatica",
    description: "Cada frase tem exatamente um erro. Arraste-a para o TIPO de desvio: concordância, regência, crase, colocação pronominal ou pontuação. Erros sutis e plausíveis.",
    difficulty: "Avancado",
    xpReward: 64,
    estimatedTime: "5 min",
    thumbnail: "gramatica-registro",
    progress: 0,
    unlocked: true,
    engine: "classify",
    skill: "Diagnóstico de erro",
    classify: {
      instruction: "Identifique a natureza do erro em cada frase e leve-a ao balde do tipo de desvio correspondente.",
      buckets: [
        { id: "concordancia", label: "Concordância", hint: "verbal ou nominal" },
        { id: "regencia", label: "Regência", hint: "preposição exigida" },
        { id: "crase", label: "Crase", hint: "uso indevido ou ausente do acento" },
        { id: "colocacao", label: "Colocação pronominal", hint: "próclise/ênclise/mesóclise" },
        { id: "pontuacao", label: "Pontuação", hint: "vírgula/ponto e vírgula" },
      ],
      items: [
        { id: "i1", text: "Devem haver razões para isso.", bucketId: "concordancia", explanation: "'Haver' impessoal não flexiona o auxiliar: 'deve haver'." },
        { id: "i2", text: "Assisti o filme premiado ontem.", bucketId: "regencia", explanation: "'Assistir' (=ver) é transitivo indireto: 'assisti ao filme'." },
        { id: "i3", text: "Voltarei à Brasília no mês que vem.", bucketId: "crase", explanation: "'Brasília' não admite artigo: 'a Brasília', sem crase." },
        { id: "i4", text: "Me disseram que você chegou.", bucketId: "colocacao", explanation: "Não se inicia frase com próclise: 'Disseram-me'." },
        { id: "i5", text: "O diretor que assumiu ontem renunciou.", bucketId: "pontuacao", explanation: "Se explicativa, faltam as vírgulas: 'O diretor, que assumiu ontem, renunciou'." },
        { id: "i6", text: "Fazem dez anos que ele partiu.", bucketId: "concordancia", explanation: "'Fazer' (tempo) é impessoal: 'Faz dez anos'." },
        { id: "i7", text: "Esqueci de pagar a conta.", bucketId: "regencia", explanation: "Pronominal, 'esquecer-se de'; não pronominal, 'esquecer a conta'. 'Esqueci de' é desvio." },
        { id: "i8", text: "Cheguei à cavalo na fazenda.", bucketId: "crase", explanation: "Não há crase antes de palavra masculina: 'a cavalo'." },
        { id: "i9", text: "Nunca vi-o tão abatido.", bucketId: "colocacao", explanation: "Palavra negativa ('nunca') atrai o pronome (próclise): 'Nunca o vi'." },
        { id: "i10", text: "Comprei pão leite e ovos, na feira.", bucketId: "pontuacao", explanation: "Falta vírgula na enumeração e há vírgula indevida antes do adjunto: 'Comprei pão, leite e ovos na feira'." },
      ],
    },
  },
];
