import type { GameDefinition } from "@/features/gamification/types";

export const grammarGames: GameDefinition[] = [
  {
    id: "grammar-hunt",
    name: "Caça ao Desvio",
    category: "gramatica",
    description:
      "Modo cronometrado: aponte a frase com desvio de concordância, regência, crase ou pontuação. Os distratores são plausíveis — leia com atenção.",
    difficulty: "Avancado",
    xpReward: 70,
    estimatedTime: "Infinito",
    thumbnail: "gramatica-revisao",
    progress: 0,
    unlocked: true,
    engine: "timed-rush",
    skill: "Norma-padrão",
    questions: [
      {
        id: "q1",
        prompt: "Qual frase apresenta desvio de concordância verbal?",
        options: [
          "Os jovens precisa de orientação crítica.",
          "A escola deve mediar leituras.",
          "As redes influenciam hábitos.",
          "O estudante revisa o texto.",
        ],
        answerIndex: 0,
        explanation: "O sujeito plural 'os jovens' exige 'precisam'.",
      },
      {
        id: "q2",
        prompt: "Qual frase contém erro de regência verbal?",
        options: [
          "Assistimos o jogo pela televisão.",
          "Assistimos ao jogo pela televisão.",
          "Obedecemos às regras combinadas.",
          "Aspiramos a uma sociedade justa.",
        ],
        answerIndex: 0,
        explanation: "No sentido de 'ver', 'assistir' é transitivo indireto: 'assistir ao jogo'.",
      },
      {
        id: "q3",
        prompt: "Em qual alternativa o uso da crase está incorreto?",
        options: [
          "Refiro-me à pessoas erradas.",
          "Cheguei à conclusão esperada.",
          "Vou à escola amanhã.",
          "Entreguei o livro à diretora.",
        ],
        answerIndex: 0,
        explanation: "Não há crase antes de palavra no plural sem artigo definido plural: 'a pessoas'.",
      },
      {
        id: "q4",
        prompt: "Qual frase apresenta desvio de concordância nominal?",
        options: [
          "É proibido entrada de estranhos.",
          "É proibida a entrada de estranhos.",
          "Seguem anexas as planilhas.",
          "Havia muitas pessoas na sala.",
        ],
        answerIndex: 0,
        explanation: "Com o substantivo determinado ('a entrada'), o adjetivo concorda: 'é proibida'.",
      },
      {
        id: "q5",
        prompt: "Qual frase tem erro de concordância com o verbo 'haver'?",
        options: [
          "Houveram muitos protestos no país.",
          "Houve muitos protestos no país.",
          "Faz dez anos que estudo aqui.",
          "Existem soluções viáveis.",
        ],
        answerIndex: 0,
        explanation: "'Haver' no sentido de 'existir' é impessoal: não vai para o plural — 'houve'.",
      },
      {
        id: "q6",
        prompt: "Qual período está pontuado de forma inadequada?",
        options: [
          "O aluno, que se esforça vence.",
          "O aluno que se esforça vence.",
          "Maria, a professora, chegou cedo.",
          "Estudei muito; portanto, passei.",
        ],
        answerIndex: 0,
        explanation: "A oração explicativa exige vírgula antes e depois; faltou a segunda vírgula: 'O aluno, que se esforça, vence.'",
      },
      {
        id: "q7",
        prompt: "Qual frase contém desvio de regência nominal?",
        options: [
          "Tenho preferência por séries do que por filmes.",
          "Tenho preferência por séries.",
          "Ele tem aversão a multidões.",
          "Sou favorável ao projeto.",
        ],
        answerIndex: 0,
        explanation: "'Preferência' não admite 'do que'; o correto é 'preferência por X a Y'.",
      },
      {
        id: "q8",
        prompt: "Qual alternativa apresenta colocação pronominal inadequada na norma-padrão?",
        options: [
          "Não vi-o desde ontem.",
          "Não o vi desde ontem.",
          "Disse-me a verdade.",
          "Quando o encontrei, sorri.",
        ],
        answerIndex: 0,
        explanation: "Palavra negativa atrai o pronome (próclise): 'Não o vi'.",
      },
      {
        id: "q9",
        prompt: "Qual frase apresenta erro de paralelismo sintático?",
        options: [
          "Gosto de ler e de filmes.",
          "Gosto de ler e de assistir a filmes.",
          "Ela estuda e trabalha.",
          "Quero saúde e tranquilidade.",
        ],
        answerIndex: 0,
        explanation: "Os termos coordenados devem ter a mesma estrutura: 'de ler e de assistir a filmes'.",
      },
      {
        id: "q10",
        prompt: "Qual frase apresenta desvio no uso do porquê?",
        options: [
          "Não sei por quê ele saiu.",
          "Não sei por que ele saiu.",
          "Ele saiu porque estava cansado.",
          "Qual é o porquê disso?",
        ],
        answerIndex: 0,
        explanation: "No interior da frase, sem pausa final, usa-se 'por que' (separado e sem acento).",
      },
      {
        id: "q11",
        prompt: "Qual período tem vírgula que separa indevidamente sujeito e verbo?",
        options: [
          "Os estudantes da rede pública, merecem mais investimento.",
          "Os estudantes da rede pública merecem mais investimento.",
          "Ontem, choveu bastante.",
          "Ele, no entanto, discordou.",
        ],
        answerIndex: 0,
        explanation: "Não se separa o sujeito ('os estudantes da rede pública') do verbo ('merecem') por vírgula.",
      },
      {
        id: "q12",
        prompt: "Qual frase contém erro de concordância com sujeito composto?",
        options: [
          "O respeito e a empatia constrói uma sociedade melhor.",
          "O respeito e a empatia constroem uma sociedade melhor.",
          "Chegaram o diretor e os professores.",
          "Faltaram água e energia.",
        ],
        answerIndex: 0,
        explanation: "Sujeito composto anteposto exige verbo no plural: 'constroem'.",
      },
      {
        id: "q13",
        prompt: "Qual alternativa emprega mal o acento indicador de crase diante de pronome?",
        options: [
          "Refiro-me à você.",
          "Refiro-me a você.",
          "Entreguei à senhora o documento.",
          "Cheguei àquele lugar.",
        ],
        answerIndex: 0,
        explanation: "Não há crase antes de pronome de tratamento como 'você': 'a você'.",
      },
      {
        id: "q14",
        prompt: "Qual frase apresenta desvio de regência com o verbo 'implicar'?",
        options: [
          "A reforma implicou em mudanças profundas.",
          "A reforma implicou mudanças profundas.",
          "Ele implicou com o colega.",
          "Isso implica responsabilidade.",
        ],
        answerIndex: 0,
        explanation: "No sentido de 'acarretar', 'implicar' é transitivo direto: 'implicou mudanças' (sem 'em').",
      },
      {
        id: "q15",
        prompt: "Qual período usa o ponto e vírgula de forma inadequada?",
        options: [
          "Comprei; pão, leite e ovos.",
          "Uns defendem a medida; outros, a rejeitam.",
          "Estudou muito; logo, foi aprovado.",
          "Há prós; há contras.",
        ],
        answerIndex: 0,
        explanation: "Não se usa ponto e vírgula entre verbo e seus complementos: 'Comprei pão, leite e ovos.'",
      },
      {
        id: "q16",
        prompt: "Qual frase apresenta erro de concordância com expressão de porcentagem?",
        options: [
          "1% dos eleitores faltaram.",
          "1% dos eleitores faltou.",
          "30% da turma foram aprovados.",
          "A maioria dos alunos chegou cedo.",
        ],
        answerIndex: 0,
        explanation: "Com '1%', o verbo fica no singular: '1% dos eleitores faltou'.",
      },
    ],
  },
  {
    id: "comma-surgeon",
    name: "Cirurgia de Vírgula",
    category: "gramatica",
    description: "Digite a palavra logo após a qual a vírgula deve entrar para corrigir ou clarear o período. Pontuação fina, sem alternativas.",
    difficulty: "Avancado",
    xpReward: 66,
    estimatedTime: "6 min",
    thumbnail: "gramatica-pontuacao",
    progress: 0,
    unlocked: true,
    engine: "fill-blank",
    skill: "Pontuação",
    fillBlank: {
      rounds: [
        {
          id: "r1",
          prompt: "Adjunto deslocado: 'Nesse contexto ___ a escola deve atuar com firmeza.' Após qual palavra entra a vírgula?",
          accepted: ["contexto"],
          explanation: "O adjunto adverbial deslocado para o início é isolado por vírgula: 'Nesse contexto, a escola...'.",
        },
        {
          id: "r2",
          prompt: "Vocativo: 'Senhores ___ o debate vai começar.' Após qual palavra entra a vírgula?",
          accepted: ["senhores"],
          explanation: "O vocativo é separado por vírgula: 'Senhores, o debate vai começar.'",
        },
        {
          id: "r3",
          prompt: "Oração reduzida deslocada: 'Ao analisar o problema ___ percebe-se a falha estrutural.' Após qual palavra entra a vírgula?",
          accepted: ["problema"],
          explanation: "A oração adverbial deslocada para o início é isolada: 'Ao analisar o problema, percebe-se...'.",
        },
        {
          id: "r4",
          prompt: "Conjunção conclusiva intercalada: 'Estudou bastante e ___ portanto, foi aprovado.' Após qual palavra entra a vírgula?",
          accepted: ["e"],
          explanation: "A conjunção intercalada 'portanto' pede vírgula antes dela: 'e, portanto, foi aprovado.'",
        },
        {
          id: "r5",
          prompt: "Aposto explicativo: 'Machado de Assis ___ autor de Dom Casmurro, criou Capitu.' Após qual palavra entra a primeira vírgula?",
          accepted: ["assis", "machado de assis"],
          explanation: "O aposto explicativo é isolado por vírgulas: 'Machado de Assis, autor de Dom Casmurro, criou Capitu.'",
        },
        {
          id: "r6",
          prompt: "Enumeração: 'Comprei pão ___ leite e ovos.' Após qual palavra entra a vírgula?",
          accepted: ["pao"],
          explanation: "Na enumeração, separam-se os itens por vírgula (exceto antes do 'e' final): 'pão, leite e ovos'.",
        },
        {
          id: "r7",
          prompt: "Oração coordenada adversativa: 'A meta era ousada ___ mas a equipe a cumpriu.' Após qual palavra entra a vírgula?",
          accepted: ["ousada"],
          explanation: "Antes da conjunção adversativa 'mas' usa-se vírgula: 'A meta era ousada, mas a equipe...'.",
        },
        {
          id: "r8",
          prompt: "Termo deslocado: 'O resultado ___ surpreendentemente, agradou a todos.' Após qual palavra entra a primeira vírgula?",
          accepted: ["resultado"],
          explanation: "O advérbio intercalado é isolado: 'O resultado, surpreendentemente, agradou a todos.'",
        },
      ],
    },
  },
  {
    id: "register-classify",
    name: "Registro Sob Pressão",
    category: "gramatica",
    description: "Arraste cada frase para o registro a que pertence: adequada à norma-padrão, coloquial/inadequada para redação, ou com desvio gramatical.",
    difficulty: "Intermediario",
    xpReward: 58,
    estimatedTime: "5 min",
    thumbnail: "gramatica-registro",
    progress: 0,
    unlocked: true,
    engine: "classify",
    skill: "Adequação de registro",
    classify: {
      instruction: "Classifique cada frase conforme sua adequação a uma redação dissertativa-argumentativa.",
      buckets: [
        { id: "padrao", label: "Norma-padrão", hint: "adequada à redação formal" },
        { id: "coloquial", label: "Coloquial", hint: "compreensível, mas informal demais" },
        { id: "desvio", label: "Desvio gramatical", hint: "erro de norma-padrão" },
      ],
      items: [
        { id: "i1", text: "A desigualdade social compromete o acesso à educação de qualidade.", bucketId: "padrao" },
        { id: "i2", text: "É fundamental que o Estado amplie os investimentos em ciência.", bucketId: "padrao" },
        { id: "i3", text: "Tipo assim, a galera não tá nem aí pra leitura.", bucketId: "coloquial" },
        { id: "i4", text: "A gente precisa mudar essa situação o quanto antes.", bucketId: "coloquial", explanation: "'A gente' é coloquial; prefira 'nós' ou estrutura impessoal." },
        { id: "i5", text: "Os dado mostra que o problema aumentou.", bucketId: "desvio", explanation: "Falta concordância: 'os dados mostram'." },
        { id: "i6", text: "Houveram muitas denúncias no período.", bucketId: "desvio", explanation: "'Haver' impessoal não vai ao plural: 'houve'." },
        { id: "i7", text: "Sob essa perspectiva, urge repensar as políticas públicas.", bucketId: "padrao" },
        { id: "i8", text: "Mano, o ENEM cobra muito repertório, sacou?", bucketId: "coloquial" },
        { id: "i9", text: "Eu vi ele saindo da escola cedo.", bucketId: "desvio", explanation: "Pronome reto como objeto: o correto é 'vi-o'." },
      ],
    },
  },
];
