export { ApiClientError, apiFetch } from "@/lib/http-client";
export { authApi } from "@/services/auth-service";
export { adminSubscriptionApi, subscriptionApi } from "@/services/subscription-service";
export { adminSupportApi, supportApi } from "@/services/support-service";
export type {
  AdminMetrics,
  AdminSubscriber,
  AdminSubscribersResponse,
  AdminSupportTicket,
  AdminSupportTicketListResponse,
  ApiEnvelope,
  CognitiveIssueRecord,
  CheckoutResponse,
  Coupon,
  Dashboard,
  Essay,
  EssayCorrection,
  EssayHistory,
  EssaySubmitResponse,
  EssayTheme,
  EssayVersion,
  Exercise,
  JobStatus,
  LearningProfile,
  Lesson,
  Module,
  NextRecommendedAction,
  AuthResponse,
  Subscription,
  SubscriptionCycle,
  SubscriptionStatus,
  SupportTicketCategory,
  SupportTicketStatus,
  User,
} from "@/types/api";
