import type { GameDefinition } from "@/features/gamification/types";

export const connectiveGames: GameDefinition[] = [
  {
    id: "connectives-precision",
    name: "Acerte o Conectivo",
    category: "coesao",
    description:
      "Modo cronometrado: escolha o conectivo que preserva a relação lógica (oposição, conclusão, causa, ressalva). A velocidade aumenta e o combo multiplica o XP.",
    difficulty: "Avancado",
    xpReward: 72,
    estimatedTime: "Infinito",
    thumbnail: "coesao-conectivos",
    progress: 0,
    unlocked: true,
    engine: "timed-rush",
    skill: "Coesão textual",
    questions: [
      {
        id: "q1",
        prompt:
          "A desigualdade digital limita a participação escolar. ___, políticas de conectividade precisam chegar primeiro às escolas públicas.",
        options: ["Portanto", "Entretanto", "Por exemplo", "Em síntese"],
        answerIndex: 0,
        explanation: "A segunda frase conclui uma consequência prática do problema apresentado.",
      },
      {
        id: "q2",
        prompt: "A leitura crítica amplia a autonomia dos jovens. ___, ela ainda é pouco estimulada em muitos ambientes escolares.",
        options: ["Logo", "Entretanto", "Assim", "Desse modo"],
        answerIndex: 1,
        explanation: "Há contraste entre o valor da leitura e sua baixa presença na escola.",
      },
      {
        id: "q3",
        prompt: "A escola deve ensinar análise de fontes. ___, precisa discutir algoritmos e consumo de informação.",
        options: ["Além disso", "Por conseguinte", "Contudo", "Em síntese"],
        answerIndex: 0,
        explanation: "A segunda ação soma uma nova frente ao mesmo eixo argumentativo.",
      },
      {
        id: "q4",
        prompt: "Muitos estudantes dominam repertórios socioculturais. ___, nem sempre conseguem conectá-los ao argumento central.",
        options: ["No entanto", "Portanto", "Assim", "Em suma"],
        answerIndex: 0,
        explanation: "O conectivo marca oposição entre conhecer repertórios e usá-los com eficiência.",
      },
      {
        id: "q5",
        prompt:
          "A proposta de intervenção indica agente, ação, meio e finalidade. ___, ela atende plenamente à Competência 5 do ENEM.",
        options: ["Dessa forma", "Embora", "Por outro lado", "Apesar disso"],
        answerIndex: 0,
        explanation: "A segunda frase apresenta a consequência positiva da estrutura citada antes.",
      },
      {
        id: "q6",
        prompt: "O acesso a livros digitais cresceu nos últimos anos. ___, parte da população ainda não possui internet estável.",
        options: ["Entretanto", "Logo", "Por isso", "Desse modo"],
        answerIndex: 0,
        explanation: "Há contraste entre o avanço tecnológico e a permanência da exclusão digital.",
      },
      {
        id: "q7",
        prompt: "A leitura amplia vocabulário e repertório. ___, contribui para argumentos mais precisos na redação.",
        options: ["Consequentemente", "Todavia", "Em contrapartida", "Mesmo assim"],
        answerIndex: 0,
        explanation: "O segundo período indica resultado direto do hábito de leitura.",
      },
      {
        id: "q8",
        prompt: "A escrita exige prática constante. ___, simulados isolados não bastam para formar bons redatores.",
        options: ["Afinal", "Entretanto", "Por exemplo", "Em conclusão"],
        answerIndex: 0,
        explanation: "O conectivo introduz a justificativa para a necessidade de prática contínua.",
      },
      {
        id: "q9",
        prompt: "O tema exige análise social ampla. ___, é necessário evitar argumentos baseados apenas em opinião pessoal.",
        options: ["Por isso", "Ainda que", "Apesar disso", "Ao contrário"],
        answerIndex: 0,
        explanation: "Evitar a opinião solta decorre da exigência de análise ampla.",
      },
      {
        id: "q10",
        prompt: "A conclusão retoma a tese. ___, apresenta uma proposta concreta para o problema discutido.",
        options: ["Além disso", "Contudo", "Embora", "Por outro lado"],
        answerIndex: 0,
        explanation: "O conectivo soma uma segunda função da conclusão.",
      },
      {
        id: "q11",
        prompt: "O repertório histórico fortalece a argumentação. ___, seu uso precisa estar ligado ao recorte temático.",
        options: ["Contudo", "Logo", "Assim", "Portanto"],
        answerIndex: 0,
        explanation: "O conectivo cria ressalva: o repertório ajuda, mas precisa ser bem articulado.",
      },
      {
        id: "q12",
        prompt: "O parágrafo apresenta causa, consequência e exemplo. ___, sua progressão fica mais clara para o corretor.",
        options: ["Com isso", "Apesar disso", "Todavia", "Em contrapartida"],
        answerIndex: 0,
        explanation: "A clareza do parágrafo é resultado da organização interna citada antes.",
      },
      {
        id: "q13",
        prompt:
          "O autor reconhece os avanços das redes sociais; ___, alerta para o encolhimento do debate público qualificado.",
        options: ["por outro lado", "por conseguinte", "do mesmo modo", "isto é"],
        answerIndex: 0,
        explanation: "Após admitir um ponto positivo, o conectivo introduz a contrapartida — uso concessivo-adversativo.",
      },
      {
        id: "q14",
        prompt:
          "As campanhas de conscientização tiveram alcance limitado; ___, é precipitado afirmar que a educação midiática fracassou.",
        options: ["ainda assim", "portanto", "por isso", "logo"],
        answerIndex: 0,
        explanation: "Mesmo diante do resultado fraco, conclui-se o contrário do esperado: relação concessiva.",
      },
      {
        id: "q15",
        prompt:
          "A política pública deve ser contínua, ___ resultados em educação só aparecem no médio prazo.",
        options: ["visto que", "a fim de que", "ainda que", "à medida que"],
        answerIndex: 0,
        explanation: "A segunda oração justifica a primeira: relação de causa, não de finalidade nem de concessão.",
      },
      {
        id: "q16",
        prompt: "O Estado ampliou o acervo das bibliotecas ___ democratizar o acesso à leitura nas periferias.",
        options: ["a fim de", "uma vez que", "por mais que", "tão logo"],
        answerIndex: 0,
        explanation: "A relação é de finalidade (objetivo da ação), não de causa nem de tempo.",
      },
      {
        id: "q17",
        prompt:
          "___ a tecnologia evolua rapidamente, a formação docente para usá-la criticamente avança em ritmo lento.",
        options: ["Embora", "Portanto", "Assim que", "Porquanto"],
        answerIndex: 0,
        explanation: "Há contraste entre dois ritmos: a oração concessiva pede 'Embora'.",
      },
      {
        id: "q18",
        prompt:
          "Os dados de leitura melhoram ___ aumentam os investimentos em mediação cultural nas escolas.",
        options: ["à medida que", "ainda que", "a fim de que", "conquanto"],
        answerIndex: 0,
        explanation: "Relação de proporção/simultaneidade entre duas variáveis que crescem juntas.",
      },
      {
        id: "q19",
        prompt:
          "A desinformação se espalha com rapidez; ___, exige respostas igualmente ágeis das plataformas e do poder público.",
        options: ["por isso", "no entanto", "em contrapartida", "isto é"],
        answerIndex: 0,
        explanation: "A segunda frase é consequência lógica da primeira — relação causal-conclusiva.",
      },
      {
        id: "q20",
        prompt:
          "A inclusão digital não se resume a distribuir aparelhos; ___, envolve letramento, conectividade e mediação pedagógica.",
        options: ["mais que isso", "por exemplo", "em resumo", "por sua vez"],
        answerIndex: 0,
        explanation: "O conectivo amplia e corrige a ideia anterior, somando complexidade ao argumento.",
      },
    ],
  },
  {
    id: "referential-cohesion",
    name: "Retomada referencial",
    category: "coesao",
    description: "Identifique a retomada que evita repetição sem gerar ambiguidade. Foco em pronomes, sinônimos e expressões resumitivas.",
    difficulty: "Avancado",
    xpReward: 64,
    estimatedTime: "5 min",
    thumbnail: "coesao-retomadas",
    progress: 0,
    unlocked: true,
    engine: "quiz",
    skill: "Coesão referencial",
    questions: [
      {
        id: "q1",
        prompt: "Em 'A tecnologia amplia o acesso, mas ela exige formação crítica', o pronome 'ela' retoma:",
        options: ["a tecnologia", "o acesso", "a formação", "a crítica"],
        answerIndex: 0,
        explanation: "O pronome retoma o núcleo do sujeito anterior, mantendo a continuidade temática.",
      },
      {
        id: "q2",
        prompt:
          "'As redes sociais conectam pessoas. ___ também concentram poder informacional.' Qual retomada é mais precisa e evita repetição?",
        options: ["Essas plataformas", "Esse fenômeno", "Tal recurso", "Esse governo"],
        answerIndex: 0,
        explanation: "'Essas plataformas' resume o referente sem empobrecer nem desviar o sentido.",
      },
      {
        id: "q3",
        prompt:
          "'O ministro anunciou o programa ao governador. Ele afirmou que a meta é ousada.' O problema dessa retomada é:",
        options: [
          "ambiguidade: 'ele' pode ser o ministro ou o governador",
          "repetição excessiva do sujeito",
          "uso indevido de sinônimo",
          "falta de conectivo conclusivo",
        ],
        answerIndex: 0,
        explanation: "Com dois referentes masculinos, o pronome 'ele' gera ambiguidade — defeito de coesão referencial.",
      },
      {
        id: "q4",
        prompt: "Qual expressão retoma 'o aquecimento global' por meio de um termo resumitivo (rotulação)?",
        options: ["esse fenômeno climático", "ele", "o mesmo", "tal qual"],
        answerIndex: 0,
        explanation: "A retomada por rótulo nomeia e categoriza o referente, enriquecendo o texto.",
      },
      {
        id: "q5",
        prompt:
          "'Os jovens leem pouco. Isso preocupa especialistas.' O pronome 'isso' retoma:",
        options: ["o fato de os jovens lerem pouco", "os jovens", "os especialistas", "a leitura"],
        answerIndex: 0,
        explanation: "O 'isso' faz retomada de toda a oração anterior (referência a um conteúdo, não a um nome).",
      },
      {
        id: "q6",
        prompt: "Qual reescrita elimina a repetição mantendo a clareza? 'A escola forma cidadãos. A escola precisa de recursos.'",
        options: [
          "A escola forma cidadãos e, para isso, precisa de recursos.",
          "A escola forma cidadãos. Ela escola precisa de recursos.",
          "A escola forma cidadãos. A mesma escola a escola precisa.",
          "A escola forma cidadãos, a escola escola precisa de recursos.",
        ],
        answerIndex: 0,
        explanation: "A conexão por 'e, para isso' funde as frases e elimina a repetição do sujeito.",
      },
      {
        id: "q7",
        prompt:
          "'O Brasil aprovou a LGPD em 2018. A legislação regula o uso de dados pessoais.' A expressão 'a legislação':",
        options: [
          "retoma a LGPD por hiperônimo, evitando repetir a sigla",
          "introduz um novo referente sem ligação",
          "gera ambiguidade com '2018'",
          "é uma repetição literal da sigla",
        ],
        answerIndex: 0,
        explanation: "'A legislação' é um termo mais geral (hiperônimo) que retoma a LGPD com elegância.",
      },
      {
        id: "q8",
        prompt:
          "Em 'Defendo a ampliação de bibliotecas e creches; tais equipamentos reduzem desigualdades', 'tais equipamentos' retoma:",
        options: ["bibliotecas e creches", "apenas creches", "a ampliação", "as desigualdades"],
        answerIndex: 0,
        explanation: "A retomada resumitiva agrupa os dois itens citados sob um rótulo comum.",
      },
    ],
  },
  {
    id: "connective-function-match",
    name: "Conectivo por função",
    category: "coesao",
    description: "Arraste cada conectivo para a relação lógica que ele estabelece. Cuidado com os que mudam de sentido conforme o contexto.",
    difficulty: "Avancado",
    xpReward: 70,
    estimatedTime: "5 min",
    thumbnail: "coesao-funcao",
    progress: 0,
    unlocked: true,
    engine: "classify",
    skill: "Função dos conectivos",
    classify: {
      instruction: "Cada conectivo abaixo expressa uma relação lógica dominante. Leve-o para o balde correto.",
      buckets: [
        { id: "oposicao", label: "Oposição / Concessão", hint: "contraste, ressalva, quebra de expectativa" },
        { id: "conclusao", label: "Conclusão / Consequência", hint: "fecha um raciocínio, indica resultado" },
        { id: "causa", label: "Causa / Explicação", hint: "justifica, aponta o porquê" },
        { id: "adicao", label: "Adição", hint: "soma argumentos no mesmo sentido" },
        { id: "finalidade", label: "Finalidade", hint: "indica objetivo, propósito" },
      ],
      items: [
        { id: "i1", text: "entretanto", bucketId: "oposicao" },
        { id: "i2", text: "ainda assim", bucketId: "oposicao", explanation: "Valor concessivo: contraria a expectativa." },
        { id: "i3", text: "por mais que", bucketId: "oposicao", explanation: "Conjunção concessiva." },
        { id: "i4", text: "portanto", bucketId: "conclusao" },
        { id: "i5", text: "por conseguinte", bucketId: "conclusao" },
        { id: "i6", text: "logo", bucketId: "conclusao", explanation: "Conclusivo, não temporal, neste uso argumentativo." },
        { id: "i7", text: "visto que", bucketId: "causa" },
        { id: "i8", text: "uma vez que", bucketId: "causa" },
        { id: "i9", text: "porquanto", bucketId: "causa", explanation: "Conjunção causal/explicativa formal." },
        { id: "i10", text: "ademais", bucketId: "adicao" },
        { id: "i11", text: "outrossim", bucketId: "adicao", explanation: "Equivale a 'além disso', soma argumentos." },
        { id: "i12", text: "a fim de que", bucketId: "finalidade" },
        { id: "i13", text: "para que", bucketId: "finalidade" },
      ],
    },
  },
];
