import type { GameDefinition } from "@/features/gamification/types";

export const connectiveGames: GameDefinition[] = [
  {
    id: "connectives-precision",
    name: "Acerte o Conectivo",
    category: "coesao",
    description: "Escolha rapidamente o conectivo que preserva progressao, contraste, causa ou consequencia.",
    difficulty: "Essencial",
    xpReward: 42,
    estimatedTime: "3 min",
    thumbnail: "coesao-conectivos",
    progress: 0,
    unlocked: true,
    rarity: "comum",
    engine: "quiz",
    skill: "Coesao",
    questions: [
      {
        id: "q1",
        prompt: "A desigualdade digital limita a participacao escolar. ___, politicas de conectividade precisam chegar primeiro as escolas publicas.",
        options: ["Portanto", "Entretanto", "Por exemplo", "Apesar disso"],
        answerIndex: 0,
        explanation: "A segunda frase conclui uma consequencia pratica do problema apresentado.",
      },
      {
        id: "q2",
        prompt: "A leitura critica amplia a autonomia dos jovens. ___, ela ainda e pouco estimulada em muitos ambientes escolares.",
        options: ["Logo", "Entretanto", "Assim", "Desse modo"],
        answerIndex: 1,
        explanation: "Ha contraste entre o valor da leitura e sua baixa presenca na escola.",
      },
      {
        id: "q3",
        prompt: "A escola deve ensinar analise de fontes. ___, precisa discutir algoritmos e consumo de informacao.",
        options: ["Alem disso", "Por conseguinte", "Contudo", "Em sintese"],
        answerIndex: 0,
        explanation: "A segunda acao soma uma nova frente ao mesmo eixo argumentativo.",
      },
      {
        id: "q4",
        prompt: "Muitos estudantes dominam repertorios socioculturais. ___, nem sempre conseguem conecta-los ao argumento central.",
        options: ["No entanto", "Portanto", "Assim", "Em suma"],
        answerIndex: 0,
        explanation: "O conectivo marca oposicao entre conhecer repertorios e usa-los com eficiencia.",
      },
      {
        id: "q5",
        prompt: "A proposta de intervencao precisa indicar agente, acao, meio e finalidade. ___, ela se torna mais completa para a Competencia 5.",
        options: ["Dessa forma", "Embora", "Por outro lado", "Apesar disso"],
        answerIndex: 0,
        explanation: "A segunda frase apresenta consequencia positiva da estrutura citada antes.",
      },
      {
        id: "q6",
        prompt: "O acesso a livros digitais cresceu nos ultimos anos. ___, parte da populacao ainda nao possui internet estavel.",
        options: ["Entretanto", "Logo", "Por isso", "Desse modo"],
        answerIndex: 0,
        explanation: "Ha contraste entre avanco tecnologico e permanencia da exclusao digital.",
      },
      {
        id: "q7",
        prompt: "A leitura amplia vocabulario e repertorio. ___, contribui para argumentos mais precisos na redacao.",
        options: ["Consequentemente", "Todavia", "Em contrapartida", "Mesmo assim"],
        answerIndex: 0,
        explanation: "O segundo periodo indica resultado direto do habito de leitura.",
      },
      {
        id: "q8",
        prompt: "A escola deve trabalhar escrita com constancia. ___, simulados isolados nao sao suficientes para formar bons redatores.",
        options: ["Afinal", "Entretanto", "Por exemplo", "Em conclusao"],
        answerIndex: 0,
        explanation: "O conectivo introduz justificativa para a necessidade de pratica continua.",
      },
      {
        id: "q9",
        prompt: "O tema exige analise social ampla. ___, e necessario evitar argumentos baseados apenas em opiniao pessoal.",
        options: ["Por isso", "Ainda que", "Apesar disso", "Ao contrario"],
        answerIndex: 0,
        explanation: "A necessidade de evitar opiniao solta decorre da exigencia de analise ampla.",
      },
      {
        id: "q10",
        prompt: "A conclusao retoma a tese. ___, apresenta uma proposta concreta para o problema discutido.",
        options: ["Alem disso", "Contudo", "Embora", "Por outro lado"],
        answerIndex: 0,
        explanation: "O conectivo soma uma segunda funcao da conclusao.",
      },
      {
        id: "q11",
        prompt: "O repertorio historico pode fortalecer a argumentacao. ___, seu uso precisa estar ligado ao recorte tematico.",
        options: ["Contudo", "Logo", "Assim", "Portanto"],
        answerIndex: 0,
        explanation: "O conectivo cria ressalva: repertorio ajuda, mas precisa ser bem articulado.",
      },
      {
        id: "q12",
        prompt: "O paragrafo apresenta causa, consequencia e exemplo. ___, sua progressao fica mais clara para o corretor.",
        options: ["Com isso", "Apesar disso", "Todavia", "Em contrapartida"],
        answerIndex: 0,
        explanation: "A clareza do paragrafo e resultado da organizacao interna citada antes.",
      },
    ],
  },
  {
    id: "referential-cohesion",
    name: "Retomada referencial",
    category: "coesao",
    description: "Identifique pronomes, sinonimos e expressoes que evitam repeticao.",
    difficulty: "Intermediario",
    xpReward: 58,
    estimatedTime: "4 min",
    thumbnail: "coesao-retomadas",
    progress: 0,
    unlocked: true,
    rarity: "raro",
    engine: "quiz",
    skill: "Coesao",
    questions: [
      {
        id: "q1",
        prompt: "Em 'A tecnologia amplia o acesso. Ela tambem exige formacao critica', o termo 'Ela' retoma:",
        options: ["A tecnologia", "A formacao", "O acesso", "A critica"],
        answerIndex: 0,
        explanation: "O pronome evita repeticao e mantem continuidade textual.",
      },
      {
        id: "q2",
        prompt: "Qual alternativa retoma 'redes sociais' com mais precisao?",
        options: ["essas plataformas", "esse governo", "essa proposta", "esse autor"],
        answerIndex: 0,
        explanation: "A expressao preserva o referente sem empobrecer a frase.",
      },
    ],
  },
];
