import type { GameDefinition } from "@/features/gamification/types";

export const duelGames: GameDefinition[] = [
  {
    id: "version-duel",
    name: "Duelo de Versões",
    category: "argumentacao",
    description: "Duas versões quase idênticas de um trecho. Decida qual tiraria nota maior e descubra a dimensão que separa as duas.",
    difficulty: "Avancado",
    xpReward: 76,
    estimatedTime: "6 min",
    thumbnail: "duelo-versoes",
    progress: 0,
    unlocked: true,
    engine: "duel",
    skill: "Julgamento de qualidade",
    tags: ["argumentacao-rasa", "texto-robotico"],
    hubs: ["texto_artificial"],
    cognitiveFocus: ["diagnosis", "refinement"],
    duel: {
      rounds: [
        {
          id: "d1",
          context: "Introdução sobre exclusão digital. Qual abre melhor a dissertação?",
          a: "A Constituição de 1988 define a educação como direito de todos; contudo, a desigualdade no acesso à tecnologia transforma esse direito em privilégio, perpetuando a exclusão digital.",
          b: "A educação é muito importante para o Brasil e para o mundo. Hoje em dia, a tecnologia mudou tudo e nem todos têm acesso, o que é um grande problema atual.",
          winner: "a",
          dimension: "repertório + tese delimitada",
          explanation: "A versão A contextualiza com repertório legitimado e fecha numa tese (direito → privilégio → exclusão). B é genérica, sem recorte nem ponto de vista.",
          tags: ["introducao-sem-tese", "repertorio-decorativo"],
        },
        {
          id: "d2",
          context: "Desenvolvimento. Qual parágrafo progride melhor?",
          a: "A desinformação é um problema. As fake news enganam as pessoas. Isso é ruim para a democracia. Precisamos resolver isso urgentemente.",
          b: "A desinformação corrói a democracia porque substitui o debate por boatos; como os algoritmos premiam o engajamento, conteúdos sensacionalistas circulam mais, o que naturaliza a mentira como argumento.",
          winner: "b",
          dimension: "progressão e nexo causal",
          explanation: "B encadeia causa e consequência (algoritmo → engajamento → naturalização). A justapõe frases curtas sem progressão (parataxe pobre).",
          tags: ["progressao-fraca", "c3"],
        },
        {
          id: "d3",
          context: "Uso de repertório. Qual articulação é melhor?",
          a: "Segundo Zygmunt Bauman, em 'Modernidade Líquida', os laços sociais se tornaram frágeis e descartáveis na contemporaneidade.",
          b: "O conceito de modernidade líquida, de Bauman, explica por que apps de relacionamento normalizam o descarte afetivo: tornam o outro substituível a um toque.",
          winner: "b",
          dimension: "articulação (uso × menção)",
          explanation: "B opera o conceito sobre o problema (gera análise). A apenas parafraseia a definição — repertório decorativo, ainda que correto.",
          tags: ["repertorio-decorativo"],
        },
        {
          id: "d4",
          context: "Conclusão. Qual proposta de intervenção é mais completa?",
          a: "Portanto, é necessário que o governo e a sociedade se conscientizem e tomem atitudes para mudar essa triste realidade o quanto antes.",
          b: "Portanto, o MEC deve inserir educação midiática no currículo, por meio de formação docente continuada, a fim de capacitar os jovens a checar fontes — com avaliação bienal de impacto.",
          winner: "b",
          dimension: "completude da intervenção (C5)",
          explanation: "B traz agente, ação, meio, finalidade e detalhamento. A é o clichê vazio do 'conscientizar', sem agente nem meio.",
          tags: ["conclusao-formula", "intervencao-incompleta", "c5"],
        },
        {
          id: "d5",
          context: "Naturalidade. Qual frase soa menos artificial?",
          a: "Outrossim, é mister salientar que a problemática em tela demanda, hodiernamente, soluções paliativas e mitigadoras.",
          b: "Além disso, o problema exige soluções concretas e imediatas, não apenas medidas que adiam o enfrentamento real.",
          winner: "b",
          dimension: "naturalidade (rebuscamento vazio)",
          explanation: "A acumula jargão pomposo ('mister', 'hodiernamente', 'em tela') sem ganho de sentido. B é formal e claro — sofisticação real ≠ palavra difícil.",
          tags: ["texto-robotico", "abstracao-excessiva"],
        },
        {
          id: "d6",
          context: "Coesão. Qual transição entre parágrafos é melhor?",
          a: "Outro ponto importante a ser abordado é a questão da saúde, que também é muito relevante nesse contexto todo.",
          b: "Se a exclusão digital limita o acesso à informação, seus efeitos extrapolam a escola e atingem também o cuidado com a saúde.",
          winner: "b",
          dimension: "coesão referencial entre parágrafos",
          explanation: "B retoma o argumento anterior e o conecta ao novo (ponte lógica). A usa a muleta 'outro ponto importante', sem ligar as ideias.",
          tags: ["conectivo-artificial", "c4"],
        },
        {
          id: "d7",
          context: "Tese. Qual é mais defensável?",
          a: "A meritocracia é uma ideia polêmica que divide opiniões e gera muitos debates acalorados na sociedade brasileira atual.",
          b: "A retórica meritocrática, ao ignorar a desigualdade de pontos de partida, transfere ao indivíduo a culpa por falhas de origem estrutural.",
          winner: "b",
          dimension: "delimitação e argumentabilidade",
          explanation: "B nomeia mecanismo e consequência (operacionalizável). A só constata que o tema é polêmico — não é tese.",
          tags: ["tese-vaga", "argumentacao-rasa"],
        },
        {
          id: "d8",
          context: "Dado estatístico. Qual emprego é mais forte?",
          a: "Dados do IBGE mostram que muitos domicílios brasileiros não têm acesso à internet, o que é preocupante.",
          b: "Se um quinto dos domicílios não tem internet (IBGE), então o ensino remoto, sem inclusão prévia, amplia o fosso que pretendia fechar.",
          winner: "b",
          dimension: "interpretação do dado",
          explanation: "B extrai uma consequência do número (dado vira prova). A apenas relata o dado e o qualifica como 'preocupante'.",
          tags: ["repertorio-decorativo", "argumentacao-rasa"],
        },
      ],
    },
  },
];
