import type { GameDefinition } from "@/features/gamification/types";

export const competencyGames: GameDefinition[] = [
  {
    id: "competency-diagnosis",
    name: "Diagnóstico de Competências",
    category: "competencias-enem",
    description:
      "Casos-limite: cada sintoma poderia tocar mais de uma competência. Identifique a competência PRINCIPALMENTE avaliada, segundo a matriz oficial.",
    difficulty: "Avancado",
    xpReward: 74,
    estimatedTime: "6 min",
    thumbnail: "competencias-diagnostico",
    progress: 0,
    unlocked: true,
    engine: "quiz",
    skill: "Matriz de correção",
    questions: [
      {
        id: "q1",
        prompt:
          "Uma redação usa conectivos corretos, mas repete a mesma ideia em todos os parágrafos, sem fazer o texto avançar. Qual competência é MAIS penalizada?",
        options: [
          "C3 — projeto de texto e progressão das ideias",
          "C4 — coesão",
          "C2 — compreensão do tema",
          "C1 — norma culta",
        ],
        answerIndex: 0,
        explanation: "Conectivos corretos preservam a C4; o problema é a falta de progressão/seleção de informações — núcleo da C3.",
      },
      {
        id: "q2",
        prompt:
          "O texto cita um repertório legítimo, mas totalmente desligado do recorte temático. O maior prejuízo recai sobre:",
        options: [
          "C2 — repertório produtivo e pertinência ao tema",
          "C3 — argumentação",
          "C5 — proposta de intervenção",
          "C4 — coesão",
        ],
        answerIndex: 0,
        explanation: "Repertório legitimado mas improdutivo (não articulado ao tema) é avaliado pela C2.",
      },
      {
        id: "q3",
        prompt:
          "A proposta de intervenção é detalhada e completa, mas fere os direitos humanos. Qual é a consequência na matriz?",
        options: [
          "C5 zerada por desrespeito aos direitos humanos",
          "C5 com nota máxima, pois é completa",
          "C2 zerada",
          "C3 reduzida pela metade",
        ],
        answerIndex: 0,
        explanation: "Mesmo completa, a proposta que viola direitos humanos zera a C5 — regra específica da matriz.",
      },
      {
        id: "q4",
        prompt:
          "O candidato escreve com excelente domínio gramatical, mas tangencia o tema, falando de um assunto vizinho. Qual competência sofre mais?",
        options: [
          "C2 — abordagem completa do tema",
          "C1 — norma culta",
          "C4 — coesão",
          "C3 — argumentação",
        ],
        answerIndex: 0,
        explanation: "Domínio gramatical preserva a C1; o tangenciamento ao recorte é falha de C2 (e, em fuga total, zera a redação).",
      },
      {
        id: "q5",
        prompt:
          "Os parágrafos são bem articulados entre si, mas dentro de cada um as frases se justapõem sem conectivos. Qual competência é mais afetada?",
        options: [
          "C4 — coesão intraparágrafo (microestrutura)",
          "C3 — argumentação",
          "C1 — norma culta",
          "C2 — tema",
        ],
        answerIndex: 0,
        explanation: "A coesão (C4) abrange tanto a articulação entre parágrafos quanto entre frases; a falha aqui é intraparágrafo.",
      },
      {
        id: "q6",
        prompt:
          "A redação tem ótimos argumentos, mas usa 'a gente', 'tá' e gírias. Qual competência é diretamente atingida?",
        options: [
          "C1 — modalidade escrita formal",
          "C3 — argumentação",
          "C2 — repertório",
          "C4 — coesão",
        ],
        answerIndex: 0,
        explanation: "Registro informal e desvios de norma pertencem à C1, mesmo com boa argumentação (C3 preservada).",
      },
      {
        id: "q7",
        prompt:
          "O texto defende um ponto de vista claro, com bons argumentos, mas conclui sem qualquer proposta de solução. O que ocorre?",
        options: [
          "C5 fica baixa por ausência de proposta de intervenção",
          "C3 é zerada",
          "C2 é zerada",
          "Nada muda, pois a argumentação está boa",
        ],
        answerIndex: 0,
        explanation: "A proposta de intervenção é exigência exclusiva da C5; sem ela, essa competência despenca, ainda que a C3 esteja sólida.",
      },
      {
        id: "q8",
        prompt:
          "A proposta existe e respeita os direitos humanos, mas não diz QUEM executará a ação. Qual competência perde pontos e por quê?",
        options: [
          "C5 — falta o elemento 'agente' na proposta",
          "C3 — falta argumento",
          "C2 — falta repertório",
          "C1 — falta norma culta",
        ],
        answerIndex: 0,
        explanation: "A C5 avalia a completude da proposta (agente, ação, meio, finalidade, detalhamento); a ausência de agente a reduz.",
      },
    ],
  },
  {
    id: "competency-classify",
    name: "Sintoma → Competência",
    category: "competencias-enem",
    description: "Arraste cada sintoma de correção para a competência que ele MAIS afeta. Vários são casos-limite que tangenciam duas competências.",
    difficulty: "Avancado",
    xpReward: 68,
    estimatedTime: "5 min",
    thumbnail: "competencias-classify",
    progress: 0,
    unlocked: true,
    engine: "classify",
    skill: "Mapeamento de competências",
    classify: {
      instruction: "Para cada sintoma, escolha a competência principalmente atingida — pense no que a matriz avalia em cada caso.",
      buckets: [
        { id: "c1", label: "C1 — Norma culta", hint: "modalidade escrita formal" },
        { id: "c2", label: "C2 — Tema e repertório", hint: "recorte e pertinência" },
        { id: "c3", label: "C3 — Argumentação", hint: "projeto de texto, progressão" },
        { id: "c4", label: "C4 — Coesão", hint: "articulação entre partes" },
        { id: "c5", label: "C5 — Intervenção", hint: "proposta detalhada" },
      ],
      items: [
        { id: "i1", text: "Repertório legítimo, porém desconectado do recorte do tema", bucketId: "c2", explanation: "Pertinência do repertório é C2, não C3." },
        { id: "i2", text: "Ideias que não progridem: o 2º parágrafo repete o 1º", bucketId: "c3", explanation: "Falta de progressão é projeto de texto — C3." },
        { id: "i3", text: "Uso recorrente de 'pra' e 'você' no texto", bucketId: "c1" },
        { id: "i4", text: "Frases justapostas sem conectivos dentro do parágrafo", bucketId: "c4" },
        { id: "i5", text: "Proposta sem o elemento 'meio' (o como)", bucketId: "c5" },
        { id: "i6", text: "Abordagem que fala do tema vizinho, tangenciando o recorte", bucketId: "c2" },
        { id: "i7", text: "Repetição da palavra 'sociedade' por falta de retomada", bucketId: "c4", explanation: "Substituição lexical é coesão — C4." },
        { id: "i8", text: "Ponto de vista frágil, sem argumentos que o sustentem", bucketId: "c3" },
        { id: "i9", text: "Erros de crase e concordância ao longo do texto", bucketId: "c1" },
        { id: "i10", text: "Proposta detalhada, mas que sugere punição violenta ilegal", bucketId: "c5", explanation: "Viola direitos humanos: zera a C5." },
      ],
    },
  },
  {
    id: "competency-rush",
    name: "Competência Relâmpago",
    category: "competencias-enem",
    description: "Modo cronometrado: classifique rápido a competência principal de cada sintoma. Casos-limite, combo e velocidade crescente.",
    difficulty: "Avancado",
    xpReward: 72,
    estimatedTime: "Infinito",
    thumbnail: "competencias-rush",
    progress: 0,
    unlocked: true,
    engine: "timed-rush",
    skill: "Reconhecimento de competências",
    questions: [
      {
        id: "q1",
        prompt: "Sintoma: conectivos corretos, mas argumentos que não avançam. Competência principal?",
        options: ["C3", "C4", "C2", "C1"],
        answerIndex: 0,
        explanation: "Progressão das ideias é C3; a coesão (C4) está preservada pelos conectivos corretos.",
      },
      {
        id: "q2",
        prompt: "Sintoma: repertório legítimo, mas desligado do tema. Competência?",
        options: ["C2", "C3", "C5", "C4"],
        answerIndex: 0,
        explanation: "Pertinência do repertório ao recorte é avaliada na C2.",
      },
      {
        id: "q3",
        prompt: "Sintoma: domínio gramatical impecável, mas o texto tangencia o tema. Competência mais afetada?",
        options: ["C2", "C1", "C4", "C3"],
        answerIndex: 0,
        explanation: "A C1 está preservada; o tangenciamento atinge a C2.",
      },
      {
        id: "q4",
        prompt: "Sintoma: frases sem conexão dentro do parágrafo. Competência?",
        options: ["C4", "C3", "C1", "C2"],
        answerIndex: 0,
        explanation: "Coesão microestrutural é C4.",
      },
      {
        id: "q5",
        prompt: "Sintoma: proposta completa, mas viola direitos humanos. O que acontece?",
        options: ["C5 zerada", "C5 máxima", "C2 zerada", "C3 reduzida"],
        answerIndex: 0,
        explanation: "Proposta que fere direitos humanos zera a C5, mesmo se completa.",
      },
      {
        id: "q6",
        prompt: "Sintoma: 'a gente' e gírias, embora a argumentação seja boa. Competência?",
        options: ["C1", "C3", "C2", "C4"],
        answerIndex: 0,
        explanation: "Registro informal é desvio de norma culta — C1.",
      },
      {
        id: "q7",
        prompt: "Sintoma: conclui sem propor solução, apesar de boa argumentação. Competência mais afetada?",
        options: ["C5", "C3", "C2", "C4"],
        answerIndex: 0,
        explanation: "A ausência de proposta atinge exclusivamente a C5.",
      },
      {
        id: "q8",
        prompt: "Sintoma: proposta sem agente nem meio. Competência?",
        options: ["C5", "C3", "C2", "C1"],
        answerIndex: 0,
        explanation: "A completude da proposta (agente, meio etc.) é avaliada na C5.",
      },
      {
        id: "q9",
        prompt: "Sintoma: repetição de 'sociedade' por falta de sinônimo/retomada. Competência?",
        options: ["C4", "C1", "C3", "C2"],
        answerIndex: 0,
        explanation: "Substituição lexical e retomada são coesão — C4.",
      },
      {
        id: "q10",
        prompt: "Sintoma: tese é apenas uma cópia do tema, sem ponto de vista. Competência mais afetada?",
        options: ["C3", "C2", "C1", "C4"],
        answerIndex: 0,
        explanation: "Falta de autoria/projeto de texto é C3 (a C2 só seria atingida se fugisse do tema).",
      },
    ],
  },
];
