import type { GameDefinition } from "@/features/gamification/types";

export const competencyGames: GameDefinition[] = [
  {
    id: "competency-diagnosis",
    name: "Diagnóstico de Competências",
    category: "competencias-enem",
    description: "Reconheça qual das cinco competências do ENEM está em jogo em cada situação. Aprofundado e com casos reais de correção.",
    difficulty: "Avancado",
    xpReward: 68,
    estimatedTime: "6 min",
    thumbnail: "competencias-diagnostico",
    progress: 0,
    unlocked: true,
    engine: "quiz",
    skill: "Matriz de correção",
    questions: [
      {
        id: "q1",
        prompt: "Problemas de conectivos e retomadas atingem principalmente qual competência?",
        options: ["Competência 4 (coesão)", "Competência 1", "Competência 2", "Competência 5"],
        answerIndex: 0,
        explanation: "A Competência 4 avalia coesão e articulação entre as partes do texto.",
      },
      {
        id: "q2",
        prompt: "Desvios de concordância, regência e ortografia pesam mais em qual competência?",
        options: ["Competência 1 (norma-padrão)", "Competência 3", "Competência 4", "Competência 5"],
        answerIndex: 0,
        explanation: "A Competência 1 mede o domínio da modalidade escrita formal.",
      },
      {
        id: "q3",
        prompt: "Fugir do tema ou tangenciá-lo prejudica diretamente qual competência?",
        options: ["Competência 2 (compreensão do tema)", "Competência 1", "Competência 4", "Competência 5"],
        answerIndex: 0,
        explanation: "A Competência 2 avalia a compreensão da proposta e a aplicação do recorte temático.",
      },
      {
        id: "q4",
        prompt: "Uma proposta de intervenção sem agente ou sem meio compromete qual competência?",
        options: ["Competência 5 (intervenção)", "Competência 2", "Competência 3", "Competência 4"],
        answerIndex: 0,
        explanation: "A Competência 5 exige proposta detalhada com agente, ação, meio, finalidade e detalhamento.",
      },
      {
        id: "q5",
        prompt: "Argumentos sem organização, sem seleção e sem progressão de ideias afetam qual competência?",
        options: ["Competência 3 (argumentação)", "Competência 1", "Competência 2", "Competência 4"],
        answerIndex: 0,
        explanation: "A Competência 3 avalia selecionar, relacionar e organizar informações em defesa de um ponto de vista.",
      },
      {
        id: "q6",
        prompt: "Texto bem escrito, mas que apenas repete o senso comum sem defender um ponto de vista, perde em qual competência?",
        options: ["Competência 3", "Competência 1", "Competência 4", "Competência 5"],
        answerIndex: 0,
        explanation: "Sem projeto de texto e autoria argumentativa, a Competência 3 é penalizada.",
      },
      {
        id: "q7",
        prompt: "Uso de repertório sociocultural pertinente e produtivo é avaliado sobretudo em qual competência?",
        options: ["Competência 2", "Competência 1", "Competência 4", "Competência 5"],
        answerIndex: 0,
        explanation: "A Competência 2 valoriza repertório legitimado e produtivo ligado ao tema.",
      },
      {
        id: "q8",
        prompt: "Uma redação com proposta que desrespeita os direitos humanos sofre penalização em qual competência?",
        options: ["Competência 5", "Competência 1", "Competência 3", "Competência 4"],
        answerIndex: 0,
        explanation: "A proposta de intervenção (C5) deve respeitar os direitos humanos, sob pena de perder pontos.",
      },
    ],
  },
  {
    id: "competency-classify",
    name: "Sintoma → Competência",
    category: "competencias-enem",
    description: "Arraste cada problema observado numa redação para a competência do ENEM que ele mais afeta.",
    difficulty: "Avancado",
    xpReward: 66,
    estimatedTime: "5 min",
    thumbnail: "competencias-classify",
    progress: 0,
    unlocked: true,
    engine: "classify",
    skill: "Mapeamento de competências",
    classify: {
      instruction: "Para cada sintoma de correção, escolha a competência mais diretamente atingida.",
      buckets: [
        { id: "c1", label: "C1 — Norma-padrão", hint: "domínio da escrita formal" },
        { id: "c2", label: "C2 — Tema e repertório", hint: "compreensão da proposta" },
        { id: "c3", label: "C3 — Argumentação", hint: "seleção e organização de ideias" },
        { id: "c4", label: "C4 — Coesão", hint: "articulação entre partes" },
        { id: "c5", label: "C5 — Intervenção", hint: "proposta detalhada" },
      ],
      items: [
        { id: "i1", text: "Erros frequentes de concordância verbal", bucketId: "c1" },
        { id: "i2", text: "Crase usada de forma incorreta", bucketId: "c1" },
        { id: "i3", text: "Tangenciamento do tema proposto", bucketId: "c2" },
        { id: "i4", text: "Repertório descontextualizado ou decorativo", bucketId: "c2" },
        { id: "i5", text: "Argumentos soltos, sem projeto de texto", bucketId: "c3" },
        { id: "i6", text: "Defesa de ponto de vista frágil e genérica", bucketId: "c3" },
        { id: "i7", text: "Ausência de conectivos entre parágrafos", bucketId: "c4" },
        { id: "i8", text: "Repetição de palavras por falta de retomada", bucketId: "c4" },
        { id: "i9", text: "Proposta sem agente nem meio", bucketId: "c5" },
        { id: "i10", text: "Proposta que viola os direitos humanos", bucketId: "c5" },
      ],
    },
  },
  {
    id: "competency-rush",
    name: "Competência Relâmpago",
    category: "competencias-enem",
    description: "Modo cronometrado: classifique rápido qual competência está em foco. Combo e velocidade crescente.",
    difficulty: "Avancado",
    xpReward: 70,
    estimatedTime: "Infinito",
    thumbnail: "competencias-rush",
    progress: 0,
    unlocked: true,
    engine: "timed-rush",
    skill: "Reconhecimento de competências",
    questions: [
      {
        id: "q1",
        prompt: "Sintoma: 'havia' escrito como 'haviam'. Qual competência?",
        options: ["C1", "C2", "C3", "C4"],
        answerIndex: 0,
        explanation: "Desvio de norma-padrão (verbo impessoal) — Competência 1.",
      },
      {
        id: "q2",
        prompt: "Sintoma: a redação não cita repertório legitimado. Qual competência?",
        options: ["C2", "C1", "C4", "C5"],
        answerIndex: 0,
        explanation: "Repertório sociocultural produtivo é avaliado na Competência 2.",
      },
      {
        id: "q3",
        prompt: "Sintoma: parágrafos sem conexão entre si. Qual competência?",
        options: ["C4", "C1", "C2", "C3"],
        answerIndex: 0,
        explanation: "Coesão e articulação entre partes — Competência 4.",
      },
      {
        id: "q4",
        prompt: "Sintoma: proposta de intervenção sem finalidade. Qual competência?",
        options: ["C5", "C2", "C3", "C4"],
        answerIndex: 0,
        explanation: "A Competência 5 exige todos os elementos da proposta, inclusive finalidade.",
      },
      {
        id: "q5",
        prompt: "Sintoma: ideias desorganizadas, sem hierarquia. Qual competência?",
        options: ["C3", "C1", "C2", "C5"],
        answerIndex: 0,
        explanation: "Seleção e organização de informações — Competência 3.",
      },
      {
        id: "q6",
        prompt: "Sintoma: o texto não aborda o recorte do tema. Qual competência?",
        options: ["C2", "C3", "C4", "C1"],
        answerIndex: 0,
        explanation: "Compreensão e aplicação do tema — Competência 2.",
      },
      {
        id: "q7",
        prompt: "Sintoma: repetição excessiva da palavra 'sociedade'. Qual competência?",
        options: ["C4", "C1", "C3", "C5"],
        answerIndex: 0,
        explanation: "Falta de retomada/substituição é problema de coesão — Competência 4.",
      },
      {
        id: "q8",
        prompt: "Sintoma: proposta fere os direitos humanos. Qual competência é zerada?",
        options: ["C5", "C2", "C3", "C4"],
        answerIndex: 0,
        explanation: "A C5 penaliza propostas que desrespeitam os direitos humanos.",
      },
      {
        id: "q9",
        prompt: "Sintoma: pontuação incorreta isolando sujeito e verbo. Qual competência?",
        options: ["C1", "C4", "C3", "C2"],
        answerIndex: 0,
        explanation: "Pontuação faz parte do domínio da norma-padrão — Competência 1.",
      },
      {
        id: "q10",
        prompt: "Sintoma: tese é só uma cópia do tema, sem ponto de vista. Qual competência?",
        options: ["C3", "C1", "C2", "C4"],
        answerIndex: 0,
        explanation: "Faltou autoria e defesa de ponto de vista — Competência 3.",
      },
    ],
  },
];
