import type { GameDefinition } from "@/features/gamification/types";

export const thesisGames: GameDefinition[] = [
  {
    id: "argument-map",
    name: "Cadeia de Toulmin",
    category: "argumentacao",
    description: "Ordene os elementos do argumento segundo o modelo de Toulmin: dado, garantia, apoio, refutação e conclusão. Várias ordens parecem válidas — só uma sustenta o raciocínio.",
    difficulty: "Avancado",
    estimatedTime: "6 min",
    thumbnail: "argumentacao-mapa",
    progress: 0,
    unlocked: true,
    engine: "order",
    skill: "Estrutura do argumento",
    order: {
      rounds: [
        {
          id: "r1",
          instruction: "Ordene segundo Toulmin: dado → garantia → apoio → conclusão.",
          items: [
            "Um quinto dos domicílios brasileiros não tem acesso à internet.",
            "Sem conexão, é impossível acompanhar o ensino mediado por tecnologia.",
            "Estudos do Cetic confirmam a correlação entre desconexão e defasagem escolar.",
            "Logo, o ensino remoto sem inclusão digital aprofunda a desigualdade educacional.",
          ],
          explanation: "Dado sustenta; garantia autoriza a inferência; apoio reforça a garantia; conclusão fecha. Inverter dado e garantia quebra a lógica.",
        },
        {
          id: "r2",
          instruction: "Ordene incluindo a refutação antecipada (concessão) antes da conclusão.",
          items: [
            "As campanhas de checagem alcançam milhões de pessoas.",
            "Informar corrige crenças falsas.",
            "É verdade que parte do público desconfia das próprias agências de checagem.",
            "Ainda assim, a ausência de checagem deixaria o terreno livre à desinformação.",
            "Portanto, a checagem, mesmo imperfeita, é indispensável.",
          ],
          explanation: "A concessão reconhece o contra-argumento; a resposta o neutraliza; a conclusão se fortalece por antecipar a objeção.",
        },
        {
          id: "r3",
          instruction: "Ordene um parágrafo argumentativo com qualificador modal.",
          items: [
            "A exposição precoce a telas tende a reduzir o tempo de atenção sustentada.",
            "Pesquisas em neurociência associam estímulos rápidos à fragmentação atencional.",
            "Disso decorre, provavelmente, maior dificuldade de leitura longa.",
            "Convém, pois, mediar o uso de telas na infância.",
          ],
          explanation: "O qualificador ('tende a', 'provavelmente') evita determinismo; apoio e conclusão acompanham o grau de certeza.",
        },
      ],
    },
  },
  {
    id: "fallacy-hunt",
    name: "Caça à Falácia",
    category: "argumentacao",
    description: "Cada trecho contém uma falácia. As quatro opções são falácias reais — identifique exatamente qual foi cometida.",
    difficulty: "Avancado",
    estimatedTime: "6 min",
    thumbnail: "argumentacao-falacia",
    progress: 0,
    unlocked: true,
    engine: "quiz",
    skill: "Validade argumentativa",
    questions: [
      {
        id: "q1",
        prompt: "'Não dá para confiar no estudo sobre clima: foi feito por um pesquisador que dirige carro.' Qual falácia?",
        options: ["Ad hominem circunstancial", "Falso dilema", "Petição de princípio", "Apelo à autoridade"],
        answerIndex: 0,
        explanation: "Desqualifica o argumento por uma circunstância da pessoa, não por seus méritos — ad hominem circunstancial.",
      },
      {
        id: "q2",
        prompt: "'Quem defende regular as redes quer, no fundo, calar a liberdade de expressão.' Qual falácia?",
        options: ["Espantalho (homem de palha)", "Falsa causa", "Derrapagem", "Equivocação"],
        answerIndex: 0,
        explanation: "Distorce a posição do oponente (regular ≠ calar) para atacar uma versão caricata — espantalho.",
      },
      {
        id: "q3",
        prompt: "'Se liberarmos o porte para um, logo todos andarão armados e o país virará faroeste.' Qual falácia?",
        options: ["Ladeira escorregadia (derrapagem)", "Ad hominem", "Petição de princípio", "Falsa analogia"],
        answerIndex: 0,
        explanation: "Encadeia consequências catastróficas sem demonstrar o nexo necessário entre os passos — ladeira escorregadia.",
      },
      {
        id: "q4",
        prompt: "'A pena de morte é justa porque é correto executar criminosos graves.' Qual falácia?",
        options: ["Petição de princípio (circularidade)", "Falso dilema", "Apelo à emoção", "Falsa causa"],
        answerIndex: 0,
        explanation: "A conclusão (é justa) reaparece como premissa (é correto executar): raciocínio circular.",
      },
      {
        id: "q5",
        prompt: "'Ou você apoia o projeto, ou está contra o desenvolvimento do país.' Qual falácia?",
        options: ["Falso dilema", "Espantalho", "Ad hominem", "Apelo à autoridade"],
        answerIndex: 0,
        explanation: "Reduz a duas opções extremas um leque que admite posições intermediárias — falso dilema.",
      },
      {
        id: "q6",
        prompt: "'As vendas caíram após a nova logo; a logo arruinou a empresa.' Qual falácia?",
        options: ["Falsa causa (post hoc)", "Derrapagem", "Petição de princípio", "Equivocação"],
        answerIndex: 0,
        explanation: "Toma sucessão temporal por causalidade, ignorando outras variáveis — post hoc ergo propter hoc.",
      },
      {
        id: "q7",
        prompt: "'Ninguém provou que o produto faz mal; logo, é seguro.' Qual falácia?",
        options: ["Apelo à ignorância", "Falso dilema", "Ad hominem", "Espantalho"],
        answerIndex: 0,
        explanation: "Converte ausência de prova de dano em prova de segurança — apelo à ignorância.",
      },
      {
        id: "q8",
        prompt: "'Banco de dados e banco de praça são bancos; logo, ambos guardam dinheiro.' Qual falácia?",
        options: ["Equivocação (ambiguidade lexical)", "Falsa analogia", "Falsa causa", "Petição de princípio"],
        answerIndex: 0,
        explanation: "Explora dois sentidos da palavra 'banco' como se fossem um só — equivocação.",
      },
    ],
  },
];
