import type { GameDefinition } from "@/features/gamification/types";

export const thesisGames: GameDefinition[] = [
  {
    id: "thesis-lab",
    name: "Laboratório de Tese",
    category: "argumentacao",
    description: "Modo cronometrado: escolha a tese mais clara, delimitada e defensável. Fuja das generalizações vazias e do senso comum.",
    difficulty: "Avancado",
    xpReward: 72,
    estimatedTime: "Infinito",
    thumbnail: "argumentacao-tese",
    progress: 0,
    unlocked: true,
    engine: "timed-rush",
    skill: "Construção de tese",
    questions: [
      {
        id: "q1",
        prompt: "Tema: leitura crítica entre jovens. Qual tese orienta melhor a redação?",
        options: [
          "A baixa leitura crítica fragiliza a autonomia juvenil e amplia a vulnerabilidade à desinformação.",
          "Ler é muito importante para todos.",
          "Os jovens usam bastante a internet hoje em dia.",
          "A escola existe para ensinar as pessoas.",
        ],
        answerIndex: 0,
        explanation: "A tese delimita problema, consequência e eixo argumentativo.",
      },
      {
        id: "q2",
        prompt: "Qual tese evita a generalização vazia?",
        options: [
          "A ausência de educação midiática na escola dificulta a verificação de fontes pelos estudantes.",
          "Tudo é culpa da sociedade.",
          "O Brasil sempre teve problemas.",
          "A tecnologia é boa e ruim ao mesmo tempo.",
        ],
        answerIndex: 0,
        explanation: "Ela aponta recorte, causa e efeito analisável.",
      },
      {
        id: "q3",
        prompt: "Tema: saúde mental na adolescência. Qual é a melhor tese?",
        options: [
          "O uso intensivo de redes sociais, somado à pressão por desempenho, agrava a ansiedade entre adolescentes.",
          "A adolescência é uma fase muito difícil da vida.",
          "Todo mundo tem problemas de saúde mental hoje.",
          "É preciso cuidar da saúde mental.",
        ],
        answerIndex: 0,
        explanation: "A tese articula dois fatores e o efeito, criando eixos de desenvolvimento.",
      },
      {
        id: "q4",
        prompt: "Qual tese é boa por ser específica e argumentável?",
        options: [
          "A invisibilidade do trabalho de cuidado feminino perpetua desigualdades econômicas entre gêneros.",
          "As mulheres trabalham muito.",
          "A desigualdade existe desde sempre.",
          "Homens e mulheres são diferentes.",
        ],
        answerIndex: 0,
        explanation: "Recorte preciso (trabalho de cuidado) ligado a uma consequência mensurável.",
      },
      {
        id: "q5",
        prompt: "Qual formulação NÃO serve como tese (é apenas constatação)?",
        options: [
          "A violência urbana cresceu nos últimos anos.",
          "A ausência de políticas de prevenção alimenta o ciclo da violência urbana.",
          "A precarização do espaço público intensifica a sensação de insegurança.",
          "A desigualdade socioeconômica é raiz estrutural da violência urbana.",
        ],
        answerIndex: 0,
        explanation: "Constatar um fato não é defender um ponto de vista: falta a relação causal a sustentar.",
      },
      {
        id: "q6",
        prompt: "Tema: preservação ambiental. Qual tese é mais defensável?",
        options: [
          "A falta de fiscalização ambiental favorece o desmatamento e compromete o futuro hídrico do país.",
          "Temos que salvar o planeta.",
          "O meio ambiente é importante para todos nós.",
          "A natureza é bonita e precisa ser cuidada.",
        ],
        answerIndex: 0,
        explanation: "A tese conecta causa (fiscalização frágil) a consequências concretas.",
      },
      {
        id: "q7",
        prompt: "Qual tese evita o tom prescritivo prematuro (propor antes de analisar)?",
        options: [
          "A escassez de mediação cultural na escola limita o desenvolvimento do gosto pela leitura.",
          "O governo deve construir mais bibliotecas imediatamente.",
          "Todos devem ler pelo menos um livro por mês.",
          "É preciso obrigar os jovens a ler mais.",
        ],
        answerIndex: 0,
        explanation: "A tese descreve e explica o problema; a proposta vem depois, na conclusão.",
      },
      {
        id: "q8",
        prompt: "Tema: trabalho infantil. Qual tese articula melhor causa e consequência?",
        options: [
          "A vulnerabilidade econômica das famílias perpetua o trabalho infantil e interrompe trajetórias escolares.",
          "Crianças não devem trabalhar.",
          "O trabalho infantil é um problema antigo.",
          "É triste ver crianças trabalhando.",
        ],
        answerIndex: 0,
        explanation: "Liga origem (vulnerabilidade) a efeitos (trabalho infantil, evasão escolar).",
      },
      {
        id: "q9",
        prompt: "Qual tese tem recorte adequado (nem amplo demais, nem estreito demais)?",
        options: [
          "A invisibilidade estatística dos povos indígenas dificulta a formulação de políticas públicas eficazes.",
          "Os indígenas são importantes para o Brasil.",
          "Falta tudo para os povos indígenas no Brasil.",
          "A questão indígena é muito complexa para resumir.",
        ],
        answerIndex: 0,
        explanation: "Recorte específico (invisibilidade estatística) com consequência clara e debatível.",
      },
      {
        id: "q10",
        prompt: "Qual tese se sustenta sem cair em achismo?",
        options: [
          "A concentração de médicos em grandes centros aprofunda a desigualdade no acesso à saúde no interior.",
          "O SUS não funciona direito.",
          "A saúde no Brasil é péssima.",
          "Médico bom é difícil de achar.",
        ],
        answerIndex: 0,
        explanation: "Aponta um fenômeno verificável (concentração) e seu efeito (desigualdade de acesso).",
      },
      {
        id: "q11",
        prompt: "Tema: cultura do cancelamento. Qual tese equilibra complexidade e clareza?",
        options: [
          "A lógica punitivista das redes substitui o debate por linchamentos virtuais, enfraquecendo a cultura democrática.",
          "Cancelar os outros é errado.",
          "As redes sociais são tóxicas.",
          "As pessoas brigam muito na internet.",
        ],
        answerIndex: 0,
        explanation: "Nomeia o mecanismo (lógica punitivista) e a consequência (enfraquecimento democrático).",
      },
      {
        id: "q12",
        prompt: "Qual tese NÃO é defensável por ser opinião pessoal sem base?",
        options: [
          "Videogames são a principal causa da violência entre jovens.",
          "A normalização do discurso de ódio nas redes estimula comportamentos violentos.",
          "A ausência de educação emocional dificulta a mediação de conflitos.",
          "A desigualdade de oportunidades alimenta tensões sociais.",
        ],
        answerIndex: 0,
        explanation: "A relação causal direta entre videogames e violência não tem respaldo: tese frágil.",
      },
      {
        id: "q13",
        prompt: "Tema: mobilidade urbana. Qual tese é mais produtiva?",
        options: [
          "A priorização histórica do transporte individual sobre o coletivo agrava a exclusão e a poluição nas cidades.",
          "O trânsito das cidades é caótico.",
          "Falta ônibus para todo mundo.",
          "Andar de carro é confortável.",
        ],
        answerIndex: 0,
        explanation: "Aponta uma causa estrutural (modelo de mobilidade) e duas consequências.",
      },
      {
        id: "q14",
        prompt: "Qual tese demonstra melhor domínio do recorte temático?",
        options: [
          "O apagamento da história afro-brasileira no currículo escolar dificulta o combate ao racismo estrutural.",
          "O racismo é muito ruim.",
          "Precisamos respeitar todas as pessoas.",
          "A escola deveria ensinar mais coisas.",
        ],
        answerIndex: 0,
        explanation: "Conecta um recorte preciso (currículo) a um problema amplo (racismo estrutural).",
      },
    ],
  },
  {
    id: "argument-map",
    name: "Cadeia Argumentativa",
    category: "argumentacao",
    description: "Arraste as etapas até a sequência que dá força ao argumento: do tópico à conclusão, passando por causa, dado e análise.",
    difficulty: "Intermediario",
    xpReward: 64,
    estimatedTime: "5 min",
    thumbnail: "argumentacao-mapa",
    progress: 0,
    unlocked: true,
    engine: "order",
    skill: "Encadeamento argumentativo",
    order: {
      rounds: [
        {
          id: "r1",
          instruction: "Ordene a cadeia argumentativa sobre exclusão digital.",
          items: [
            "A exclusão digital reproduz desigualdades educacionais.",
            "Isso ocorre porque o ensino mediado por tecnologia exige acesso à internet.",
            "Dados do IBGE indicam que milhões de lares seguem sem conexão adequada.",
            "Assim, estudantes pobres acumulam defasagens difíceis de reverter.",
          ],
          explanation: "Tópico → causa → dado/repertório → consequência: a ordem dá sustentação progressiva.",
        },
        {
          id: "r2",
          instruction: "Ordene a cadeia sobre desinformação.",
          items: [
            "A desinformação ameaça a qualidade do debate público.",
            "Algoritmos priorizam engajamento, favorecendo conteúdos sensacionalistas.",
            "O caso da Cambridge Analytica mostra o potencial manipulador desse modelo.",
            "Logo, urge investir em educação midiática nas escolas.",
          ],
          explanation: "Tese → mecanismo/causa → repertório → conclusão com encaminhamento.",
        },
        {
          id: "r3",
          instruction: "Ordene a cadeia sobre saúde mental e redes sociais.",
          items: [
            "O uso excessivo de redes sociais afeta a saúde mental dos jovens.",
            "A comparação constante alimenta ansiedade e insatisfação.",
            "Pesquisas associam o tempo de tela ao aumento de sintomas depressivos.",
            "Portanto, é preciso promover o uso consciente da tecnologia.",
          ],
          explanation: "Afirmação → explicação do porquê → evidência → conclusão.",
        },
      ],
    },
  },
  {
    id: "fallacy-hunt",
    name: "Caça à Falácia",
    category: "argumentacao",
    description: "Identifique o problema lógico do argumento: generalização apressada, falsa causa, apelo à emoção, ataque pessoal e mais.",
    difficulty: "Avancado",
    xpReward: 70,
    estimatedTime: "6 min",
    thumbnail: "argumentacao-falacia",
    progress: 0,
    unlocked: true,
    engine: "quiz",
    skill: "Validade argumentativa",
    questions: [
      {
        id: "q1",
        prompt: "'Conheço dois jovens que não leem; logo, a juventude não lê.' Qual é a falha?",
        options: ["Generalização apressada", "Falsa causa", "Apelo à autoridade", "Petição de princípio"],
        answerIndex: 0,
        explanation: "Conclui-se sobre o todo a partir de poucos casos não representativos.",
      },
      {
        id: "q2",
        prompt: "'As notas caíram depois que adotaram celulares; o celular causou a queda.' Qual é a falha?",
        options: ["Falsa causa (correlação ≠ causa)", "Generalização apressada", "Falso dilema", "Apelo à emoção"],
        answerIndex: 0,
        explanation: "Coincidência temporal não prova relação causal — pode haver outras variáveis.",
      },
      {
        id: "q3",
        prompt: "'Ou proibimos as redes sociais, ou perderemos uma geração inteira.' Qual é a falha?",
        options: ["Falso dilema", "Falsa causa", "Ataque pessoal", "Apelo à autoridade"],
        answerIndex: 0,
        explanation: "Reduz a duas opções extremas um problema que admite alternativas intermediárias.",
      },
      {
        id: "q4",
        prompt: "'Não vou debater com você sobre clima porque você nem é cientista.' Qual é a falha?",
        options: ["Ataque pessoal (ad hominem)", "Falso dilema", "Generalização apressada", "Petição de princípio"],
        answerIndex: 0,
        explanation: "Desqualifica a pessoa em vez de refutar o argumento.",
      },
      {
        id: "q5",
        prompt: "'Pense nas crianças! Por isso devemos aprovar a lei sem discussão.' Qual é a falha?",
        options: ["Apelo à emoção", "Falsa causa", "Apelo à autoridade", "Falso dilema"],
        answerIndex: 0,
        explanation: "Substitui o raciocínio por comoção, evitando o debate sobre o mérito.",
      },
      {
        id: "q6",
        prompt: "'Isso é verdade porque está escrito em um livro famoso.' Qual é a falha?",
        options: ["Apelo à autoridade (mal aplicado)", "Falsa causa", "Falso dilema", "Generalização apressada"],
        answerIndex: 0,
        explanation: "A fama da fonte não garante a verdade; é preciso avaliar os argumentos.",
      },
      {
        id: "q7",
        prompt: "'A leitura é boa porque ler faz bem.' Qual é a falha?",
        options: ["Petição de princípio (circularidade)", "Falsa causa", "Apelo à emoção", "Ataque pessoal"],
        answerIndex: 0,
        explanation: "A conclusão repete a premissa em outras palavras, sem prová-la.",
      },
      {
        id: "q8",
        prompt: "'Sempre foi assim, então deve continuar assim.' Qual é a falha?",
        options: ["Apelo à tradição", "Falso dilema", "Falsa causa", "Generalização apressada"],
        answerIndex: 0,
        explanation: "O fato de algo ser antigo não justifica, por si só, sua manutenção.",
      },
    ],
  },
];
