import type { GameDefinition } from "@/features/gamification/types";

export const thesisGames: GameDefinition[] = [
  {
    id: "thesis-lab",
    name: "Laboratório de Tese",
    category: "argumentacao",
    description:
      "Modo cronometrado: as quatro teses são defensáveis — escolha a MAIS delimitada e operacionalizável (com recorte, relação causal clara e desdobramento argumentativo).",
    difficulty: "Avancado",
    xpReward: 78,
    estimatedTime: "Infinito",
    thumbnail: "argumentacao-tese",
    progress: 0,
    unlocked: true,
    engine: "timed-rush",
    skill: "Construção de tese",
    questions: [
      {
        id: "q1",
        prompt: "Tema: leitura crítica entre jovens. Qual é a MELHOR tese (mais delimitada e argumentável)?",
        options: [
          "A lacuna em educação midiática na escola básica limita a capacidade dos jovens de avaliar fontes, ampliando sua exposição à desinformação.",
          "A baixa leitura crítica é um problema sério que afeta toda a juventude brasileira.",
          "A leitura crítica precisa ser mais valorizada pela sociedade e pela escola.",
          "Diversos fatores históricos e culturais explicam por que os jovens leem pouco hoje.",
        ],
        answerIndex: 0,
        explanation: "Só a 1ª tem recorte (educação midiática na escola básica), causa e consequência operacionalizáveis. As outras são amplas, vagas ou só anunciam complexidade.",
      },
      {
        id: "q2",
        prompt: "Tema: trabalho de cuidado. Qual tese sustenta melhor uma dissertação?",
        options: [
          "A naturalização do trabalho de cuidado como 'função feminina' invisibiliza sua dimensão econômica e perpetua a disparidade salarial de gênero.",
          "O trabalho de cuidado é fundamental e merece mais reconhecimento na sociedade.",
          "As mulheres ainda enfrentam muitos desafios no mercado de trabalho atual.",
          "A desigualdade de gênero é um problema estrutural que vem de longa data.",
        ],
        answerIndex: 0,
        explanation: "A 1ª nomeia o mecanismo (naturalização → invisibilização → disparidade), gerando eixos. As demais constatam ou generalizam.",
      },
      {
        id: "q3",
        prompt: "Qual formulação NÃO serve como tese, por ser mera constatação?",
        options: [
          "A violência urbana aumentou nas capitais brasileiras na última década.",
          "A ausência de políticas de prevenção realimenta o ciclo da violência urbana.",
          "A precarização do espaço público intensifica a percepção de insegurança.",
          "A desigualdade socioeconômica constitui raiz estrutural da violência urbana.",
        ],
        answerIndex: 0,
        explanation: "Constatar um fato não defende ponto de vista; falta a relação a ser sustentada. As outras três propõem nexos causais.",
      },
      {
        id: "q4",
        prompt: "Qual tese evita o vício prescritivo (propor solução antes de analisar o problema)?",
        options: [
          "A escassez de mediação cultural na escola compromete o desenvolvimento do hábito de leitura.",
          "O governo deve construir bibliotecas em todos os municípios imediatamente.",
          "Todos os jovens precisam ler ao menos um livro por mês.",
          "É preciso obrigar as escolas a adotarem programas de leitura.",
        ],
        answerIndex: 0,
        explanation: "A tese deve descrever/explicar; a proposta vem na conclusão. As demais já saltam para a intervenção.",
      },
      {
        id: "q5",
        prompt: "Tema: meritocracia. Qual tese tem recorte mais preciso?",
        options: [
          "A retórica meritocrática, ao ignorar a desigualdade de pontos de partida, transfere ao indivíduo a culpa por falhas de origem estrutural.",
          "A meritocracia é uma ideia que gera muita polêmica no debate atual.",
          "Nem sempre o esforço é recompensado de forma justa na sociedade.",
          "O mérito é importante, mas existem desigualdades que precisam ser consideradas.",
        ],
        answerIndex: 0,
        explanation: "A 1ª aponta o mecanismo (ignorar pontos de partida → culpabilização individual). As outras são opinativas e vagas.",
      },
      {
        id: "q6",
        prompt: "Qual tese é frágil por embutir uma relação causal SEM respaldo?",
        options: [
          "Os videogames são a principal causa da violência entre adolescentes.",
          "A naturalização do discurso de ódio nas redes reduz as barreiras à violência.",
          "A ausência de educação emocional dificulta a mediação de conflitos.",
          "A desigualdade de oportunidades acirra tensões sociais.",
        ],
        answerIndex: 0,
        explanation: "A causalidade direta videogame→violência é desmentida pela literatura: tese insustentável (falsa causa).",
      },
      {
        id: "q7",
        prompt: "Tema: cultura do cancelamento. Qual tese equilibra complexidade e clareza?",
        options: [
          "A lógica punitivista das redes, ao substituir o contraditório pelo linchamento, enfraquece a tolerância exigida pela cultura democrática.",
          "O cancelamento é uma forma de justiça que as redes sociais criaram.",
          "As redes sociais se tornaram ambientes muito tóxicos atualmente.",
          "Cancelar pessoas pode ser positivo ou negativo dependendo do caso.",
        ],
        answerIndex: 0,
        explanation: "A 1ª nomeia o mecanismo e a consequência democrática; as demais opinam sem delimitar.",
      },
      {
        id: "q8",
        prompt: "Tema: mobilidade urbana. Qual tese é mais produtiva?",
        options: [
          "A prioridade histórica ao transporte individual sobre o coletivo, no planejamento urbano, agrava simultaneamente a exclusão e a crise ambiental.",
          "O trânsito nas grandes cidades brasileiras está cada vez mais caótico.",
          "Faltam investimentos em transporte público de qualidade no país.",
          "A mobilidade urbana é um tema importante para a qualidade de vida.",
        ],
        answerIndex: 0,
        explanation: "A 1ª aponta causa estrutural (modelo de planejamento) e duas consequências articuladas; as demais constatam.",
      },
      {
        id: "q9",
        prompt: "Qual tese demonstra melhor domínio do recorte?",
        options: [
          "O apagamento da história afro-brasileira no currículo escolar dificulta o enfrentamento do racismo estrutural.",
          "O racismo é um problema grave que precisa ser combatido por todos.",
          "É necessário promover mais respeito e igualdade entre as pessoas.",
          "A escola tem um papel importante na formação dos cidadãos.",
        ],
        answerIndex: 0,
        explanation: "A 1ª liga um recorte específico (currículo) a um problema amplo (racismo estrutural); as outras são genéricas.",
      },
      {
        id: "q10",
        prompt: "Tema: saúde mental e redes. Qual tese é mais defensável (evita determinismo)?",
        options: [
          "O uso intensivo de redes, ao estimular a comparação social constante, contribui para o aumento de quadros de ansiedade entre adolescentes.",
          "As redes sociais causam depressão em todos os adolescentes.",
          "A internet é a culpada pelos problemas de saúde mental dos jovens.",
          "Quem usa muito o celular fica sempre com a saúde mental abalada.",
        ],
        answerIndex: 0,
        explanation: "A 1ª usa 'contribui para' (relação probabilística, defensável); as demais afirmam causalidade absoluta, frágil.",
      },
      {
        id: "q11",
        prompt: "Qual tese tem o melhor verbo de tese (preciso, não vago)?",
        options: [
          "A concentração de médicos nos grandes centros aprofunda a desigualdade no acesso à saúde no interior.",
          "A saúde pública no Brasil enfrenta diversos problemas conhecidos.",
          "O acesso à saúde varia bastante de uma região para outra.",
          "É preciso pensar em soluções para a saúde no interior do país.",
        ],
        answerIndex: 0,
        explanation: "'Aprofunda' estabelece relação verificável entre causa e efeito; as demais usam verbos vagos ou só descrevem.",
      },
      {
        id: "q12",
        prompt: "Tema: fake news. Qual tese articula causa e efeito de forma mais analítica?",
        options: [
          "A arquitetura das plataformas, ao premiar o engajamento em vez da veracidade, cria incentivos econômicos à circulação de desinformação.",
          "As fake news são um problema muito sério dos tempos atuais.",
          "Muita gente acredita em notícias falsas na internet hoje.",
          "É preciso combater a desinformação que circula nas redes.",
        ],
        answerIndex: 0,
        explanation: "A 1ª revela o mecanismo estrutural (incentivo econômico do design); as outras constatam ou prescrevem sem analisar.",
      },
    ],
  },
  {
    id: "argument-map",
    name: "Cadeia de Toulmin",
    category: "argumentacao",
    description: "Ordene os elementos do argumento segundo o modelo de Toulmin: dado, garantia, apoio, refutação e conclusão. Várias ordens parecem válidas — só uma sustenta o raciocínio.",
    difficulty: "Avancado",
    xpReward: 70,
    estimatedTime: "6 min",
    thumbnail: "argumentacao-mapa",
    progress: 0,
    unlocked: true,
    engine: "order",
    skill: "Estrutura do argumento",
    order: {
      rounds: [
        {
          id: "r1",
          instruction: "Ordene segundo Toulmin: dado → garantia → apoio → conclusão.",
          items: [
            "Um quinto dos domicílios brasileiros não tem acesso à internet (dado).",
            "Sem conexão, é impossível acompanhar o ensino mediado por tecnologia (garantia que liga dado e conclusão).",
            "Estudos do Cetic confirmam a correlação entre desconexão e defasagem escolar (apoio à garantia).",
            "Logo, o ensino remoto sem inclusão digital aprofunda a desigualdade educacional (conclusão).",
          ],
          explanation: "Dado sustenta; garantia autoriza a inferência; apoio reforça a garantia; conclusão fecha. Inverter dado e garantia quebra a lógica.",
        },
        {
          id: "r2",
          instruction: "Ordene incluindo a refutação antecipada (concessão) antes da conclusão.",
          items: [
            "As campanhas de checagem alcançam milhões de pessoas (dado).",
            "Informar corrige crenças falsas (garantia).",
            "É verdade que parte do público desconfia das próprias agências de checagem (refutação/concessão).",
            "Ainda assim, a ausência de checagem deixaria o terreno livre à desinformação (resposta à refutação).",
            "Portanto, a checagem, mesmo imperfeita, é indispensável (conclusão).",
          ],
          explanation: "A concessão reconhece o contra-argumento; a resposta o neutraliza; a conclusão se fortalece por antecipar a objeção.",
        },
        {
          id: "r3",
          instruction: "Ordene um parágrafo argumentativo com qualificador modal.",
          items: [
            "A exposição precoce a telas tende a reduzir o tempo de atenção sustentada (alegação com qualificador 'tende a').",
            "Pesquisas em neurociência associam estímulos rápidos à fragmentação atencional (apoio).",
            "Disso decorre, provavelmente, maior dificuldade de leitura longa (consequência modalizada).",
            "Convém, pois, mediar o uso de telas na infância (conclusão prudente).",
          ],
          explanation: "O qualificador ('tende a', 'provavelmente') evita determinismo; apoio e conclusão acompanham o grau de certeza.",
        },
      ],
    },
  },
  {
    id: "fallacy-hunt",
    name: "Caça à Falácia",
    category: "argumentacao",
    description: "Cada trecho contém uma falácia. As quatro opções são falácias reais — identifique exatamente qual foi cometida.",
    difficulty: "Avancado",
    xpReward: 72,
    estimatedTime: "6 min",
    thumbnail: "argumentacao-falacia",
    progress: 0,
    unlocked: true,
    engine: "quiz",
    skill: "Validade argumentativa",
    questions: [
      {
        id: "q1",
        prompt: "'Não dá para confiar no estudo sobre clima: foi feito por um pesquisador que dirige carro.' Qual falácia?",
        options: ["Ad hominem circunstancial", "Falso dilema", "Petição de princípio", "Apelo à autoridade"],
        answerIndex: 0,
        explanation: "Desqualifica o argumento por uma circunstância da pessoa, não por seus méritos — ad hominem circunstancial.",
      },
      {
        id: "q2",
        prompt: "'Quem defende regular as redes quer, no fundo, calar a liberdade de expressão.' Qual falácia?",
        options: ["Espantalho (homem de palha)", "Falsa causa", "Derrapagem", "Equivocação"],
        answerIndex: 0,
        explanation: "Distorce a posição do oponente (regular ≠ calar) para atacar uma versão caricata — espantalho.",
      },
      {
        id: "q3",
        prompt: "'Se liberarmos o porte para um, logo todos andarão armados e o país virará faroeste.' Qual falácia?",
        options: ["Ladeira escorregadia (derrapagem)", "Ad hominem", "Petição de princípio", "Falsa analogia"],
        answerIndex: 0,
        explanation: "Encadeia consequências catastróficas sem demonstrar o nexo necessário entre os passos — ladeira escorregadia.",
      },
      {
        id: "q4",
        prompt: "'A pena de morte é justa porque é correto executar criminosos graves.' Qual falácia?",
        options: ["Petição de princípio (circularidade)", "Falso dilema", "Apelo à emoção", "Falsa causa"],
        answerIndex: 0,
        explanation: "A conclusão (é justa) reaparece como premissa (é correto executar): raciocínio circular.",
      },
      {
        id: "q5",
        prompt: "'Ou você apoia o projeto, ou está contra o desenvolvimento do país.' Qual falácia?",
        options: ["Falso dilema", "Espantalho", "Ad hominem", "Apelo à autoridade"],
        answerIndex: 0,
        explanation: "Reduz a duas opções extremas um leque que admite posições intermediárias — falso dilema.",
      },
      {
        id: "q6",
        prompt: "'As vendas caíram após a nova logo; a logo arruinou a empresa.' Qual falácia?",
        options: ["Falsa causa (post hoc)", "Derrapagem", "Petição de princípio", "Equivocação"],
        answerIndex: 0,
        explanation: "Toma sucessão temporal por causalidade, ignorando outras variáveis — post hoc ergo propter hoc.",
      },
      {
        id: "q7",
        prompt: "'Ninguém provou que o produto faz mal; logo, é seguro.' Qual falácia?",
        options: ["Apelo à ignorância", "Falso dilema", "Ad hominem", "Espantalho"],
        answerIndex: 0,
        explanation: "Converte ausência de prova de dano em prova de segurança — apelo à ignorância.",
      },
      {
        id: "q8",
        prompt: "'Banco de dados e banco de praça são bancos; logo, ambos guardam dinheiro.' Qual falácia?",
        options: ["Equivocação (ambiguidade lexical)", "Falsa analogia", "Falsa causa", "Petição de princípio"],
        answerIndex: 0,
        explanation: "Explora dois sentidos da palavra 'banco' como se fossem um só — equivocação.",
      },
    ],
  },
];
