import type { GameDefinition } from "@/features/gamification/types";

export const structureGames: GameDefinition[] = [
  {
    id: "essay-assembly",
    name: "Monte a Redação",
    category: "estrutura",
    description: "Organize introducao, desenvolvimento e conclusao em uma sequencia logica de redacao ENEM.",
    difficulty: "Intermediario",
    xpReward: 74,
    estimatedTime: "6 min",
    thumbnail: "estrutura-monte-redacao",
    progress: 0,
    unlocked: true,
    rarity: "epico",
    engine: "sequence",
    skill: "Estrutura logica",
    questions: [
      {
        id: "q1",
        prompt: "Organize os blocos da redacao na estrutura correta.",
        options: ["Introducao", "Desenvolvimento", "Conclusao", "Banco de frases"],
        answerIndex: 0,
        explanation: "Uma redacao ENEM coerente apresenta contextualizacao e tese, desenvolve argumentos e fecha com proposta de intervencao.",
      },
    ],
  },
  {
    id: "paragraph-flow",
    name: "Fluxo do paragrafo",
    category: "estrutura",
    description: "Ordene topico frasal, explicacao, exemplo e fechamento.",
    difficulty: "Essencial",
    xpReward: 50,
    estimatedTime: "4 min",
    thumbnail: "estrutura-paragrafo",
    progress: 0,
    unlocked: true,
    rarity: "comum",
    engine: "sequence",
    skill: "Estrutura",
    questions: [
      {
        id: "q1",
        prompt: "Qual ordem deixa o desenvolvimento mais claro?",
        options: ["Topico frasal > explicacao > exemplo > fechamento", "Exemplo > proposta > tese > titulo", "Fechamento > exemplo > tema > agente", "Repertorio > titulo > conclusao > causa"],
        answerIndex: 0,
        explanation: "A ordem conduz a ideia central antes de provar e concluir o raciocinio.",
      },
    ],
  },
  {
    id: "intervention-builder",
    name: "Construtor de intervencao",
    category: "estrutura",
    description: "Monte agente, acao, meio, finalidade e detalhamento da proposta.",
    difficulty: "Avancado",
    xpReward: 82,
    estimatedTime: "7 min",
    thumbnail: "estrutura-intervencao",
    progress: 0,
    unlocked: true,
    rarity: "epico",
    engine: "quiz",
    skill: "Competencia 5",
    questions: [
      {
        id: "q1",
        prompt: "Qual proposta apresenta agente, acao, meio e finalidade?",
        options: [
          "O MEC deve criar clubes de leitura, por meio de formacao docente e acervo digital, para ampliar leitura critica.",
          "O governo deve ajudar mais.",
          "As pessoas precisam se conscientizar.",
          "E necessario melhorar tudo.",
        ],
        answerIndex: 0,
        explanation: "A proposta detalha quem age, o que faz, como faz e para qual objetivo.",
      },
    ],
  },
  {
    id: "competency-diagnosis",
    name: "Diagnostico de competencias",
    category: "competencias-enem",
    description: "Reconheca qual competencia do ENEM esta sendo avaliada em cada situacao.",
    difficulty: "Intermediario",
    xpReward: 60,
    estimatedTime: "5 min",
    thumbnail: "competencias-diagnostico",
    progress: 0,
    unlocked: true,
    rarity: "raro",
    engine: "quiz",
    skill: "Competencias ENEM",
    questions: [
      {
        id: "q1",
        prompt: "Problemas de conectivos e retomadas atingem principalmente qual competencia?",
        options: ["Competencia 4", "Competencia 1", "Competencia 2", "Competencia 5"],
        answerIndex: 0,
        explanation: "A Competencia 4 avalia coesao e articulacao textual.",
      },
    ],
  },
  {
    id: "daily-sprint",
    name: "Sprint diario",
    category: "desafios-diarios",
    description: "Uma pratica curta para manter ritmo sem transformar estudo em grind.",
    difficulty: "Essencial",
    xpReward: 40,
    estimatedTime: "3 min",
    thumbnail: "daily-sprint",
    progress: 0,
    unlocked: true,
    rarity: "comum",
    engine: "quiz",
    skill: "Rotina",
    questions: [
      {
        id: "q1",
        prompt: "Qual acao de 10 minutos mais melhora a escrita hoje?",
        options: ["Revisar uma tese e um conectivo", "Abrir varias abas sem escrever", "Copiar repertorios sem contexto", "Contar apenas XP"],
        answerIndex: 0,
        explanation: "Rotina pequena e objetiva gera consistencia real.",
      },
    ],
  },
];
