import type { GameDefinition } from "@/features/gamification/types";

export const structureGames: GameDefinition[] = [
  {
    id: "essay-assembly",
    name: "Monte a Redação",
    category: "estrutura",
    description:
      "Arraste os blocos para introdução, desenvolvimento e conclusão. No nível difícil há distratores que precisam ficar de fora do texto.",
    difficulty: "Avancado",
    xpReward: 84,
    estimatedTime: "7 min",
    thumbnail: "estrutura-monte-redacao",
    progress: 0,
    unlocked: true,
    engine: "sequence",
    skill: "Estrutura lógica",
    questions: [
      {
        id: "q1",
        prompt: "Organize os blocos da redação na estrutura correta.",
        options: ["Introdução", "Desenvolvimento", "Conclusão", "Banco de frases"],
        answerIndex: 0,
        explanation:
          "Uma redação ENEM coerente contextualiza e apresenta a tese, desenvolve argumentos e fecha com proposta de intervenção.",
      },
    ],
  },
  {
    id: "paragraph-flow",
    name: "Fluxo do Parágrafo",
    category: "estrutura",
    description: "Reordene períodos cuja coesão depende de catáfora, retomada e progressão tema→rema. Mais de uma ordem parece possível — só uma encadeia de fato.",
    difficulty: "Avancado",
    xpReward: 70,
    estimatedTime: "6 min",
    thumbnail: "estrutura-paragrafo",
    progress: 0,
    unlocked: true,
    engine: "order",
    skill: "Progressão textual",
    order: {
      rounds: [
        {
          id: "r1",
          instruction: "Reordene este parágrafo. Atenção à catáfora e aos conectivos que fixam a ordem.",
          items: [
            "Um dado sintetiza o impasse da inclusão digital brasileira.",
            "Segundo o IBGE, um quinto dos domicílios não tem acesso à internet.",
            "Essa carência, longe de ser apenas técnica, reproduz desigualdades históricas.",
            "Afinal, sem conexão, o estudante pobre fica alijado do ensino mediado por tecnologia.",
            "Trata-se, portanto, de uma barreira que aprofunda a exclusão social.",
          ],
          explanation: "O 1º período anuncia cataforicamente 'um dado'; o 2º o revela; 'essa carência' retoma; 'afinal' justifica; 'portanto' conclui.",
        },
        {
          id: "r2",
          instruction: "Reordene mantendo a progressão tema→rema (o rema de um vira tema do seguinte).",
          items: [
            "A leitura crítica é uma competência cada vez mais rara entre jovens.",
            "Essa raridade decorre, em parte, da hegemonia do conteúdo audiovisual rápido.",
            "Tal hegemonia, por sua vez, premia o engajamento imediato em detrimento da reflexão.",
            "Como resultado, forma-se um leitor que reage, mas pouco analisa.",
            "Reverter esse quadro exige mediação escolar deliberada e contínua.",
          ],
          explanation: "Cada período retoma o rema anterior ('raridade' → 'hegemonia' → 'leitor que reage'), garantindo encadeamento; o último propõe a saída.",
        },
        {
          id: "r3",
          instruction: "Reordene esta introdução com contextualização, problematização e tese.",
          items: [
            "A Constituição de 1988 erigiu a educação como direito de todos e dever do Estado.",
            "Décadas depois, contudo, o acesso à tecnologia educacional permanece estratificado.",
            "Esse descompasso entre norma e realidade evidencia a face digital da desigualdade.",
            "Cabe, pois, examinar suas raízes e delinear caminhos de superação.",
          ],
          explanation: "Contextualização (1988) → 'contudo' problematiza → 'esse descompasso' encapsula e tese → 'cabe, pois' encaminha a discussão.",
        },
      ],
    },
  },
  {
    id: "intervention-builder",
    name: "Anatomia da Intervenção",
    category: "estrutura",
    description: "Classifique cada trecho no elemento da proposta (Competência 5). Cuidado com os casos-limite entre meio e detalhamento, e entre ação e finalidade.",
    difficulty: "Avancado",
    xpReward: 80,
    estimatedTime: "6 min",
    thumbnail: "estrutura-intervencao",
    progress: 0,
    unlocked: true,
    engine: "classify",
    skill: "Competência 5",
    classify: {
      instruction: "Cada fragmento desempenha UM papel na proposta de intervenção. Leve-o ao elemento correto — alguns são borderline de propósito.",
      buckets: [
        { id: "agente", label: "Agente", hint: "quem executa" },
        { id: "acao", label: "Ação", hint: "o verbo central da proposta" },
        { id: "meio", label: "Meio/Modo", hint: "como (instrumento/método)" },
        { id: "finalidade", label: "Finalidade", hint: "para quê (objetivo)" },
        { id: "detalhamento", label: "Detalhamento", hint: "qualifica/condiciona um elemento" },
      ],
      items: [
        { id: "i1", text: "o Ministério da Educação, em articulação com as redes estaduais", bucketId: "agente", explanation: "Agente composto; a articulação aqui especifica QUEM, não o meio." },
        { id: "i2", text: "deve implementar uma trilha de letramento midiático", bucketId: "acao" },
        { id: "i3", text: "por meio de plataformas abertas e formação continuada de docentes", bucketId: "meio" },
        { id: "i4", text: "a fim de reduzir a vulnerabilidade dos jovens à desinformação", bucketId: "finalidade" },
        { id: "i5", text: "priorizando municípios com menores índices de proficiência leitora", bucketId: "detalhamento", explanation: "Gerúndio que CONDICIONA a ação (recorte), não o método em si." },
        { id: "i6", text: "com avaliação de impacto a cada dois anos", bucketId: "detalhamento" },
        { id: "i7", text: "o Poder Legislativo", bucketId: "agente" },
        { id: "i8", text: "mediante campanhas em redes sociais e parcerias com checadores", bucketId: "meio" },
        { id: "i9", text: "para que o eleitor distinga fato de boato", bucketId: "finalidade" },
        { id: "i10", text: "criar selos de verificação para conteúdos políticos", bucketId: "acao", explanation: "Verbo nuclear da proposta (o QUE se faz)." },
      ],
    },
  },
];
