import type { GameDefinition } from "@/features/gamification/types";

export const structureGames: GameDefinition[] = [
  {
    id: "essay-assembly",
    name: "Monte a Redação",
    category: "estrutura",
    description:
      "Arraste os blocos para introdução, desenvolvimento e conclusão. No nível difícil há distratores que precisam ficar de fora.",
    difficulty: "Avancado",
    xpReward: 84,
    estimatedTime: "7 min",
    thumbnail: "estrutura-monte-redacao",
    progress: 0,
    unlocked: true,
    engine: "sequence",
    skill: "Estrutura lógica",
    questions: [
      {
        id: "q1",
        prompt: "Organize os blocos da redação na estrutura correta.",
        options: ["Introdução", "Desenvolvimento", "Conclusão", "Banco de frases"],
        answerIndex: 0,
        explanation:
          "Uma redação ENEM coerente contextualiza e apresenta a tese, desenvolve argumentos e fecha com proposta de intervenção.",
      },
    ],
  },
  {
    id: "paragraph-flow",
    name: "Fluxo do Parágrafo",
    category: "estrutura",
    description: "Arraste as frases até a sequência que dá progressão ao parágrafo: tópico frasal, desenvolvimento, repertório e arremate.",
    difficulty: "Intermediario",
    xpReward: 62,
    estimatedTime: "5 min",
    thumbnail: "estrutura-paragrafo",
    progress: 0,
    unlocked: true,
    engine: "order",
    skill: "Progressão textual",
    order: {
      rounds: [
        {
          id: "r1",
          instruction: "Ordene este parágrafo de desenvolvimento sobre exclusão digital.",
          items: [
            "A exclusão digital agrava as desigualdades educacionais no Brasil.",
            "Isso ocorre porque o ensino remoto pressupõe acesso estável à internet.",
            "Segundo o IBGE, milhões de domicílios ainda não possuem conexão adequada.",
            "Logo, estudantes de baixa renda ficam à margem das oportunidades de aprendizagem.",
          ],
          explanation: "Tópico frasal → causa → repertório/dado → consequência: a progressão conduz do problema ao impacto.",
        },
        {
          id: "r2",
          instruction: "Ordene este parágrafo sobre o papel da leitura crítica.",
          items: [
            "A leitura crítica é essencial para a formação de cidadãos autônomos.",
            "Ela permite avaliar fontes e identificar discursos manipuladores.",
            "O caso da desinformação em eleições recentes evidencia esse risco.",
            "Portanto, estimular a leitura na escola é uma medida de defesa democrática.",
          ],
          explanation: "Tese do parágrafo → explicação → exemplo concreto → conclusão parcial.",
        },
        {
          id: "r3",
          instruction: "Ordene esta introdução completa.",
          items: [
            "A Constituição de 1988 assegura a educação como direito de todos.",
            "Na prática, contudo, o acesso à tecnologia educacional permanece desigual.",
            "Essa contradição revela a persistência da exclusão digital no país.",
            "Cabe analisar suas causas e propor caminhos para superá-la.",
          ],
          explanation: "Contextualização → problematização → tese → encaminhamento da discussão.",
        },
      ],
    },
  },
  {
    id: "intervention-builder",
    name: "Monte a Intervenção",
    category: "estrutura",
    description: "Arraste cada trecho para o elemento da proposta de intervenção (Competência 5): agente, ação, meio, finalidade e detalhamento.",
    difficulty: "Avancado",
    xpReward: 82,
    estimatedTime: "6 min",
    thumbnail: "estrutura-intervencao",
    progress: 0,
    unlocked: true,
    engine: "classify",
    skill: "Competência 5",
    classify: {
      instruction: "Uma proposta completa tem 5 elementos. Classifique cada trecho no elemento que ele representa.",
      buckets: [
        { id: "agente", label: "Agente", hint: "quem executa a ação" },
        { id: "acao", label: "Ação", hint: "o que será feito" },
        { id: "meio", label: "Meio/Modo", hint: "como será feito" },
        { id: "finalidade", label: "Finalidade", hint: "para quê / objetivo" },
        { id: "detalhamento", label: "Detalhamento", hint: "informação que aprofunda" },
      ],
      items: [
        { id: "i1", text: "O Ministério da Educação", bucketId: "agente" },
        { id: "i2", text: "as secretarias estaduais de educação", bucketId: "agente" },
        { id: "i3", text: "deve criar clubes de leitura nas escolas", bucketId: "acao" },
        { id: "i4", text: "ampliar o acervo das bibliotecas públicas", bucketId: "acao" },
        { id: "i5", text: "por meio de formação continuada de professores", bucketId: "meio" },
        { id: "i6", text: "mediante parcerias com editoras e ONGs", bucketId: "meio" },
        { id: "i7", text: "a fim de fortalecer a leitura crítica dos jovens", bucketId: "finalidade" },
        { id: "i8", text: "para reduzir a vulnerabilidade à desinformação", bucketId: "finalidade" },
        { id: "i9", text: "priorizando regiões com menores índices de leitura", bucketId: "detalhamento", explanation: "Detalhamento qualifica a ação, indicando recorte ou condição." },
        { id: "i10", text: "com avaliação semestral dos resultados", bucketId: "detalhamento" },
      ],
    },
  },
];
